-- Websites for the clients whose own site was confirmed on the web, used only
-- to fetch the brand icon shown beside the name. The handful whose domain was
-- ambiguous -- several unrelated companies of the same name, or no site at all
-- -- are deliberately left null and will be filled in from the client panel.
--
-- Only fills a null: a website typed into the panel is a person's decision and
-- outranks this list, including on a re-run.
UPDATE "Account" AS a
SET "website" = v.website
FROM (VALUES
  ('Adventist Healthcare', 'https://adventisthealthcare.com'),
  ('Aegis Medical Group', 'https://aegismedicalgroup.com'),
  ('agilon health', 'https://agilonhealth.com'),
  ('Alliance for Integrated Care of New York', 'https://aiconys.com'),
  ('Amite County Medical Services', 'https://acmsinc.org'),
  ('ArchesMed', 'https://archesmed.com'),
  ('Atlas Oncology Partners', 'https://atlasoncpartners.com'),
  ('Baptist Health (AR)', 'https://baptist-health.org'),
  ('Bookmark Medical', 'https://bookmarkmedical.com'),
  ('Cano Health', 'https://canohealth.com'),
  ('Cardiovascular Associates of America', 'https://cvausa.com'),
  ('Carle Health', 'https://carle.org'),
  ('Carolina Pines Regional Medical Center', 'https://cprmc.com'),
  ('Catalyst Health Group', 'https://catalysthealthgroup.net'),
  ('Center for Primary Care', 'https://centerforprimarycare.com'),
  ('Christie Clinic', 'https://christieclinic.com'),
  ('Citadel', 'https://citadelhealth.com'),
  ('Complete Health', 'https://completehealth.com'),
  ('ClareMedica Health Partners', 'https://claremedica.com'),
  ('ConvenientMD', 'https://convenientmd.com'),
  ('CVFP Medical Group', 'https://cvfp.net'),
  ('Derry Medical Center', 'https://dmcprimarycare.com'),
  ('DTC Family Health', 'https://dtcfamilyhealth.com'),
  ('Edinger Medical Group', 'https://edingermedicalgroup.com'),
  ('Evergreen Nephrology', 'https://evergreennephrology.com'),
  ('Family Practice of Cadillac', 'https://familypracticeofcadillac.com'),
  ('First Medical Associates', 'https://drsfirst.com'),
  ('First Valley Medical Group', 'https://firstvalleymedicalgroup.com'),
  ('Gather Health', 'https://gatherhealth.com'),
  ('Genuine Health Group', 'https://genuinehealthgroup.com'),
  ('Glacier Medical Associates', 'https://glaciermedicalassociates.com'),
  ('Granger Medical Clinic', 'https://grangermedical.com'),
  ('Greater Good Health', 'https://greatergoodhealth.com'),
  ('HarmonyCares', 'https://harmonycares.com'),
  ('HealthStar Physicians', 'https://healthstartn.org'),
  ('HealthTexas Medical Group', 'https://healthtexas.org'),
  ('Herself Health', 'https://herself-health.com'),
  ('Holzer Health System', 'https://holzer.org'),
  ('Hopscotch Primary Care', 'https://hellohopscotch.com'),
  ('Hudson Headwaters Health Network', 'https://hhhn.org'),
  ('Ilumed', 'https://ilumed.com'),
  ('iMA Medical Group', 'https://imamedicalgroup.com'),
  ('Innovacare Health', 'https://innovacarehealth.com'),
  ('Island Doctors', 'https://islanddoctors.com'),
  ('IntraCare Premier ACO', 'https://theintracare.com'),
  ('Jefferson City Medical Group', 'https://jcmg.org'),
  ('Kaiser Foundation Health Plan of Colorado', 'https://kp.org'),
  ('Kaiser Foundation Health Plan of the Mid-Atlantic States', 'https://kp.org'),
  ('Kaiser Permanente Nevada', 'https://kp.org'),
  ('Lifespark', 'https://lifespark.com'),
  ('Loudoun Medical Group', 'https://lmgdoctors.com'),
  ('Matter Health', 'https://matterhealthcare.com'),
  ('MediSys Health Network', 'https://medisyshealth.org'),
  ('MedNetOne Health Solutions', 'https://mednetone.com'),
  ('MFM Health', 'https://mfmhealth.com'),
  ('Millennium Physician Group', 'https://millenniumphysician.com'),
  ('Mountain Laurel Medical Center', 'https://mtnlaurel.org'),
  ('NeueHealth MSO', 'https://neuehealth.com'),
  ('North East Medical Services', 'https://nems.org'),
  ('Northern Ohio Medical Specialists Healthcare', 'https://nomshealthcare.com'),
  ('Northwest Permanente Physicians', 'https://northwest.permanente.org'),
  ('Ogden Clinic', 'https://ogdenclinic.com'),
  ('Olmsted Medical Center Physicians', 'https://olmmed.org'),
  ('On Belay Health Solutions', 'https://onbelayhealthsolutions.com'),
  ('OnPoint Medical Group', 'https://opmedgroup.com'),
  ('Palm Medical Centers', 'https://palmmedicalcenters.com'),
  ('Physicians Primary Care', 'https://ppcswfl.com'),
  ('Primary Medical Care Center and Urgent Care Clinic', 'https://primarymed.com'),
  ('PrimeHealth Physicians', 'https://phpmds.com'),
  ('Primus Health Network', 'https://primushealthnetwork.com'),
  ('Privia Health', 'https://priviahealth.com'),
  ('Rancho Family Medical Group', 'https://ranchofamilymed.com'),
  ('SC House Calls', 'https://schousecalls.com'),
  ('SFP Health Group', 'https://sfphealthgroup.com'),
  ('Southeast Primary Care Partners', 'https://southeastpcp.com'),
  ('Sprinter Health', 'https://sprinterhealth.com'),
  ('Summit Medical Group', 'https://summitmedical.com'),
  ('Tampa General Hospital', 'https://tgh.org'),
  ('TECQ Partners', 'https://tecqpartners.com'),
  ('The Harbor Health Team', 'https://harborhealth.com'),
  ('TriValley Medical Group', 'https://trivalleymedicalgroup.com'),
  ('TriValley Primary Care', 'https://trivalleypc.com'),
  ('Tryon Medical Partners', 'https://tryonmed.com'),
  ('Tufts Medicine', 'https://tuftsmedicine.org'),
  ('U.S. Renal Care', 'https://usrenalcare.com'),
  ('Upperline Health', 'https://upperlinehealth.com'),
  ('Upward Health', 'https://upwardhealth.com'),
  ('Valora Medical Group', 'https://valoramedical.com'),
  ('Vanguard Medical Group', 'https://vanguardmedgroup.com'),
  ('VillageMD', 'https://villagemd.com'),
  ('Washington Permanente Medical Group', 'https://washington.permanente.org')
) AS v(name, website)
WHERE a."name" = v.name AND a."website" IS NULL;
