#!/usr/bin/env python3
"""Write the migration that applies one accounts report.

Takes the report records, the plan, and a decisions file naming the display name
and aliases for each new account — those are judgement calls, so the script
refuses to invent them.

Emits, in order:
  1. INSERT ... ON CONFLICT (name) DO NOTHING for the new accounts.
  2. UPDATE ... FROM (VALUES ...) for every row in the report, stamping reportAsOf.

Never emitted, by design: DELETE, DROP, any rename of "name" or "aliases", and
any write to "liveDate" or "archivedAt". Those four are the whole safety story —
see SKILL.md.

Usage:
  python3 generate_migration.py <report.json> <plan.json> <decisions.json> \
      <as-of YYYY-MM-DD> <out-dir>

decisions.json:
  {"new_accounts": {"<exact report string>": {"name": "...", "aliases": [...]}}}
"""
import json
import re
import sys
from datetime import datetime
from pathlib import Path

COLUMNS = [
    ("Account Health", "health", "text"),
    ("Active Products", "products", "products"),
    ("EHR", "ehr", "text"),
    ("Segment Group", "segment", "text"),
    ("Billing State/Province (text only)", "billing_state", "text"),
    ("Account Owner", "account_owner", "text"),
    ("CSM Name", "csm_name", "text"),
    ("Total Current Contracted HIE Members", "hie_members", "int"),
    ("Total Current Contracted Quality Members", "quality_members", "int"),
    ("Total Current Contracted Risk Members", "risk_members", "int"),
    ("Current ARR", "arr", "int"),
    ("CARR", "carr", "int"),
    ("Renewal Date", "renewal_date", "date"),
    ("Last Activity", "last_activity", "date"),
    ("First Closed Won Date", "first_closed_won", "date"),
]
SET_CLAUSE = [
    ('"health"', "v.health"), ('"products"', "v.products"), ('"ehr"', "v.ehr"),
    ('"segment"', "v.segment"), ('"billingState"', "v.billing_state"),
    ('"accountOwner"', "v.account_owner"), ('"csmName"', "v.csm_name"),
    ('"hieMembers"', "v.hie_members::int"), ('"qualityMembers"', "v.quality_members::int"),
    ('"riskMembers"', "v.risk_members::int"), ('"arr"', "v.arr::int"), ('"carr"', "v.carr::int"),
    ('"renewalDate"', "v.renewal_date::timestamp"), ('"lastActivityAt"', "v.last_activity::timestamp"),
    ('"firstClosedWon"', "v.first_closed_won::timestamp"),
]


def q(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def lit(value, kind):
    if kind == "int":
        return "NULL" if value in (None, "") else str(int(float(value)))
    if kind == "date":
        if value in (None, ""):
            return "NULL"
        return "'" + datetime.strptime(value, "%m/%d/%Y").strftime("%Y-%m-%d") + "'"
    if kind == "products":
        items = [p.strip() for p in (value or "").split(";") if p.strip()]
        return q(json.dumps(items, separators=(",", ":")))
    return q(value)


def slug(name):
    return "acct-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def build(recs, plan, decisions, as_of):
    by_name = {r["Account Name"]: r for r in recs}
    target = dict(plan["matched"])

    new_accounts = []
    for raw in plan["new"]:
        d = decisions.get("new_accounts", {}).get(raw)
        if not d or not d.get("name"):
            raise SystemExit(
                f'No decision for new account {raw!r}.\n'
                "Add it to decisions.json with a display name and aliases — the display\n"
                "name is a judgement call (keep real disambiguators, move FKA/AKA text\n"
                "into aliases) and this script will not guess it."
            )
        target[raw] = d["name"]
        new_accounts.append((d["name"], d.get("aliases", [])))

    rows = []
    for raw in sorted(target, key=lambda r: target[r].lower()):
        rec = by_name[raw]
        cells = [q(target[raw])] + [lit(rec.get(src), kind) for src, _, kind in COLUMNS]
        rows.append("  (" + ", ".join(cells) + ")")

    head = f"""-- The {as_of} accounts report.
--
-- Generated by .claude/skills/accounts-report-update. {len(recs)} report rows:
-- {len(plan['matched'])} accounts already in the hub, {len(plan['new'])} new.
--
-- Nothing is deleted: {len(plan['dropped'])} account(s) that earlier reports covered are
-- absent from this one and keep their rows and their old figures, with
-- reportAsOf saying how old. Nothing is renamed, because Insight.client holds
-- the display name and a rename would orphan its feedback. liveDate and
-- archivedAt are never written here — one is hand-entered, the other is a
-- decision, and neither appears in any report.
"""
    parts = [head]
    if new_accounts:
        parts.append(
            "\n-- New accounts. ON CONFLICT so re-running is a no-op, and so a name already\n"
            "-- added by hand in the UI is left alone.\n"
            'INSERT INTO "Account" ("id", "name", "aliases") VALUES\n'
            + ",\n".join(
                f'  ({q(slug(n))}, {q(n)}, {q(json.dumps(a, separators=(",", ":")))})'
                for n, a in new_accounts
            )
            + '\nON CONFLICT ("name") DO NOTHING;\n'
        )
    parts.append(
        f"\n-- The figures, for all {len(rows)} rows in the report.\n"
        'UPDATE "Account" a SET\n'
        + ",\n".join(f"  {col:<17}= {expr}" for col, expr in SET_CLAUSE)
        + ",\n  " + '"reportAsOf"'.ljust(17) + f"= '{as_of}'::timestamp\n"
        "FROM (VALUES\n"
        + ",\n".join(rows)
        + "\n) AS v(\n  name, "
        + ", ".join(alias for _, alias, _ in COLUMNS)
        + '\n)\nWHERE a."name" = v.name;\n'
    )
    return "".join(parts)


if __name__ == "__main__":
    if len(sys.argv) < 6:
        raise SystemExit(__doc__)
    report, planf, decf, as_of, outdir = sys.argv[1:6]
    datetime.strptime(as_of, "%Y-%m-%d")
    sql = build(json.load(open(report)), json.load(open(planf)), json.load(open(decf)), as_of)
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "migration.sql").write_text(sql)
    print(f"wrote {out / 'migration.sql'} ({len(sql)} bytes)")
