// Generated from the CI Launcher tool's public data (adiguindy-17.github.io/navina-ci-launcher)
// on 2026-09-08. Category/subgroup order mirrors that tool's own sidebar grouping.
export interface SeedCompetitorSource {
  label: string;
  url: string;
  type: string;
}

export interface SeedCompetitor {
  name: string;
  category: string;
  subgroup: string | null;
  positioning: string | null;
  website: string | null;
  overview: string | null;
  keyFacts: string | null;
  differentiation: string | null;
  lastUpdated: string | null;
  sortOrder: number;
  sources: SeedCompetitorSource[];
}

export const SEED_COMPETITORS: SeedCompetitor[] = [
  {
    name: "Reveleer",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / HCC / Chart Review",
    website: "https://www.reveleer.com/",
    overview: "Reveleer is a risk adjustment and quality management platform focused on retrospective HCC coding and chart review automation. Primarily serves health plans, payers, and risk-bearing organizations. Uses AI/NLP for bulk chart review — processing large volumes of records post-visit to identify missed HCC codes. Strong in the payer market but limited in point-of-care physician workflows. Does not integrate directly into EHR at the point of care.",
    keyFacts: "– Founded: 2016 · HQ: Alpharetta, GA\n– Funding: ~$170M raised (Series D, Warburg Pincus lead) — acquired by Datavant in 2023\n– ~300–400 employees\n– Core: retrospective chart review, HCC suspecting from claims+clinical data, quality/STARS\n– EHR: reads data but no bidirectional EHR-native push to physician at point of care\n– Contracts: historically 36-month rigid contracts (reported customer friction)\n– Customers: health plans, Medicare Advantage plans, ACOs\n– No ambient documentation capability",
    differentiation: "– Retrospective only: processes charts after visits, not during physician encounter\n– No point-of-care clinician workflow — stops at back office / coding teams\n– No ambient AI / no note generation\n– 36-month rigid contracts reported vs. Navina's flexibility\n– Fragmented modules: separate tools for coding, quality, analytics\n– No independent clinical studies showing physician adoption or burnout reduction\n– Navina reaches the physician; Reveleer reaches the coder",
    lastUpdated: "2025-06-07",
    sortOrder: 0,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Reveleer-32031faa1fb780fe9057f2184360a739", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/18uGczD3ueLZB9HYp1pjx2wlRncFGGNDX9GyjEmpq1X0/edit", type: "overview" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1MnBhRl0NYI11zgpI5vIfMaoLXQS7PQLA", type: "folder" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1WgVz4qF1nZqVM2GNESgh-hlDLGttdo7y/view", type: "summary" },
    ],
  },
  {
    name: "Stanson Health",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / Clinical Decision Support",
    website: "https://premierinc.com/stanson-health",
    overview: "Stanson Health is a clinical decision support (CDS) platform acquired by Premier Inc. in 2020. Now branded under Premier's technology suite. Core product: AI-powered clinical alerts embedded in EHR workflows — flags inappropriate orders, supports HCC risk coding, and surfaces evidence-based recommendations at the point of care. Primarily retrospective workflow. Sells to health systems and hospitals. No ambient documentation capability.",
    keyFacts: "– Acquired by Premier Inc. (2020) — not independent, part of a large GPO/technology company\n– EHR integrations: Epic, Cerner, and others via HL7/FHIR\n– Workflow: primarily retrospective HCC review + CDS alerts, not prospective point-of-care suspecting\n– No ambient AI / no note generation\n– Pricing: enterprise, typically bundled with Premier membership\n– Customers: large health systems, academic medical centers",
    differentiation: "– Alert follow rate: 42–64% vs. Navina 90% HCC address rate\n– Capture rate: 26–40% vs. Navina 77% acceptance rate\n– Stanson relies on structured EHR data; Navina reads unstructured docs, scanned files, HIE, ambient\n– No suspecting engine for new diagnoses — primarily recapture of known codes\n– No independent clinical validation studies (PHYX/AAFP equivalent)\n– Being part of Premier limits go-to-market agility vs. purpose-built VBC platform",
    lastUpdated: "2025-06-07",
    sortOrder: 1,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Stanson-Health-2cc31faa1fb780dcb6c0dae2a2a6debe", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1kbhmY_fuF8SZsOfBwuB3WBxXORcCQVv72fQZ1pMN7C0/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1u2Klh6O-HD1Totkpmp2sXSJq9A_a-h8JD9W1Xylit9A/edit", type: "battlecard" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1rJt_bQgrPJffq1S1Wb9TOx4DLbBpTl2r", type: "folder" },
      { label: "Demo Summary", url: "https://docs.google.com/document/d/1r_GPbWON8Jra59pxysyexfcmJMyKs5PaoQj-4UF7qFY/edit", type: "summary" },
      { label: "Epic & Stanson — New OPA/CDI Doc", url: "https://drive.google.com/file/d/1j4Kcsg3IFGpFO_2aS3dzetR8DVrIYAIA/view", type: "document" },
    ],
  },
  {
    name: "Foresee Medical",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment",
    website: "https://www.foreseemed.com/",
    overview: null,
    keyFacts: null,
    differentiation: null,
    lastUpdated: "2025-06-07",
    sortOrder: 2,
    sources: [
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1SHsjVw0WTyRHNadDl9S2G5X92An5J2VJ", type: "folder" },
    ],
  },
  {
    name: "Keebler Health",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment",
    website: "https://keebler.health/",
    overview: "Keebler Health is an LLM-native risk adjustment platform founded in 2023, headquartered in Durham, NC. Processes unstructured clinical documentation to surface missed HCC coding opportunities for value-based care organizations. Raised $23M total ($16M Series A led by Flare Capital Partners, April 2026). ~27 employees. Targets physician groups, MSOs, ACOs, and MA-focused providers. No named customers publicly confirmed.",
    keyFacts: "– Founded: 2023 · HQ: Durham, NC\n– Funding: ~$23M total ($7M seed + $16M Series A led by Flare Capital Partners, April 2026)\n– Employees: ~27\n– Core: LLM-native HCC coding from unstructured clinical docs, retrospective + concurrent\n– Expanding into RADV audit readiness workflows\n– No quality/HEDIS module\n– No ambient documentation\n– No named enterprise customers publicly confirmed",
    differentiation: "– Early stage (founded 2023) vs. Navina's production-scale platform (1,300+ clinics, 20,000+ clinicians)\n– No quality/HEDIS capability\n– No ambient documentation\n– No independent clinical validation studies\n– No named customers publicly confirmed\n– Retrospective/concurrent focus vs. Navina's prospective point-of-care suspecting",
    lastUpdated: "2025-06-07",
    sortOrder: 3,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Keebler-Health-33d31faa1fb780578967e41672ef9c5c", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1RtTHF0wCQnvBPbrnR8Sur5g5uv3McseW-91sITnwWcM/edit", type: "overview" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1kYdk44mb0c3kGp6fMDHCYR1ScXlsgnEx", type: "folder" },
      { label: "Demo Screenshots", url: "https://drive.google.com/drive/folders/1BcHQrBQ-b84iH3kgrtLPBFQU5cJjzyFy", type: "screenshots" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1BkvXq8p5ZnLw3dCcbwOKgP1-THawUa0-/view", type: "summary" },
    ],
  },
  {
    name: "Evidently",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / HCC",
    website: "https://www.evidently.com/",
    overview: "Evidently is a risk adjustment and HCC coding platform targeting value-based care organizations and Medicare Advantage plans. Focused on prospective and retrospective HCC workflows. Early-stage company with limited public information on product depth and customer scale.",
    keyFacts: "– Focus: HCC risk adjustment, prospective and retrospective coding\n– Target: ACOs, Medicare Advantage, value-based care organizations\n– Stage: early stage — limited public funding and customer data\n– No confirmed ambient documentation capability\n– No confirmed quality/HEDIS module",
    differentiation: "– Limited public information — verify details via web search\n– No confirmed ambient documentation or quality capability\n– No published clinical validation studies\n– Early stage vs. Navina's production-scale, KLAS-validated platform",
    lastUpdated: "2025-06-07",
    sortOrder: 4,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Evidently-35731faa1fb78005b85cf59b0afed52a", type: "notion" },
      { label: "Screenshots Folder", url: "https://drive.google.com/drive/folders/1rOWOCaowpUtlytx2kveQ8T_3kjf9IvSc", type: "screenshots" },
    ],
  },
  {
    name: "Inferscience",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / Clinical NLP",
    website: "https://www.inferscience.com/",
    overview: "Inferscience is a clinical NLP and risk adjustment platform that uses natural language processing to extract HCC-relevant diagnoses and clinical evidence from physician notes and records. Focused primarily on retrospective chart analysis and HCC coding automation. Targets health plans and risk-bearing provider organizations.",
    keyFacts: "– Focus: NLP-based HCC extraction from clinical documentation\n– Workflow: primarily retrospective chart analysis\n– Target: health plans, payers, risk-bearing organizations\n– Technology: clinical NLP on unstructured text\n– Limited public information on scale, funding, and named customers",
    differentiation: "– Background NLP tool vs. Navina's real-time point-of-care physician interface\n– No physician-facing workflow — results go to coders/analysts, not clinicians\n– No ambient documentation\n– No quality/HEDIS module\n– Navina reaches the physician during the visit; Inferscience processes charts in the back office",
    lastUpdated: "2025-06-07",
    sortOrder: 5,
    sources: [
    ],
  },
  {
    name: "Charta Health",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / Chart Review",
    website: "https://www.chartahealth.com/",
    overview: "Charta Health is a pre-bill AI chart review platform focused on coding accuracy, revenue integrity, payer compliance, and retrospective HCC review. Primarily a post-encounter, retrospective review layer — used by payer coding teams for documentation audits and undercoding detection. Supports autonomous coding review, revenue discovery, payer compliance audits, and basic quality reporting. Claims integration support for dozens of EHRs, but this appears to be data-ingestion for downstream review rather than a true point-of-care clinician-facing workflow. Both founders are ex-Rockset (acquired by OpenAI).",
    keyFacts: "– Focus: pre-bill AI chart review — coding accuracy, revenue integrity, payer compliance, retrospective HCC\n– Target: health plans, Medicare Advantage payers, coding teams\n– Workflow: post-encounter retrospective review; not a prospective or point-of-care tool\n– Founded: 2023, HQ: San Francisco, CA\n– Employees: ~65–70\n– Funding: ~$30M total — $22M Series A (July 2025, led by Bain Capital Ventures)\n– No prospective coding workflow — no new-condition suspecting/identification confirmed publicly\n– No ambient AI documentation\n– No care management platform\n– Limited quality/HEDIS workflow depth\n– No AI assistant/chatbot layer",
    differentiation: "– Retrospective/post-bill chart review only vs. Navina's prospective point-of-care workflow\n– Payer-focused vs. Navina's provider/physician-first approach\n– No physician-facing EHR-embedded interface at point of care\n– No ambient documentation\n– No advanced HCC suspecting (new condition identification) confirmed\n– Navina creates the clinical signal during the encounter; Charta audits charts after the fact",
    lastUpdated: "2026-06-09",
    sortOrder: 6,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Charta-Health-36b31faa1fb780459067d22dc66b9a28", type: "notion" },
      { label: "Executive Summary", url: "https://docs.google.com/document/d/1I25WrskW37qLg37HwnTYzEEXznjvdyF4PznpuA2grt0/edit", type: "document" },
      { label: "Navina vs Charta/Fold/MedChartScan (slides 1-2)", url: "https://docs.google.com/presentation/d/1pjIKEgSanmNfROJDWEXxD9iExxVt3dLbvCN9J6Jpf7A/edit", type: "comparison" },
    ],
  },
  {
    name: "MedChartScan",
    category: "HCC / Risk Adj.",
    subgroup: null,
    positioning: "Risk Adjustment / Document Processing",
    website: "https://medchartscan.io/",
    overview: "MedChartScan is a retrospective chart review and document processing platform for HCC risk adjustment. Focuses on scanning and analyzing clinical documentation — faxes, scanned records, medical charts — to identify missed HCC codes for health plans and MA organizations. Primarily an automated document processing service.",
    keyFacts: "– Focus: automated chart and document scanning for HCC coding\n– Target: health plans, Medicare Advantage organizations\n– Workflow: retrospective bulk document processing\n– Technology: document scanning and NLP for HCC extraction\n– Limited public information on scale or funding",
    differentiation: "– Retrospective document processing vs. Navina's real-time prospective intelligence\n– No physician-facing interface at point of care\n– No ambient documentation\n– No quality/HEDIS capability\n– Back-office service vs. Navina's clinician workflow tool",
    lastUpdated: "2025-06-07",
    sortOrder: 7,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/MedChartScan-36b31faa1fb78015863fe496d04b0d5e", type: "notion" },
      { label: "Executive Summary", url: "https://docs.google.com/document/d/1KPuqFFN5t3BWv5NRAkF0JK25-lMTy59uEmpfzpSIRqM/edit", type: "document" },
      { label: "Navina vs Charta/Fold/MedChartScan (slides 1, 4)", url: "https://docs.google.com/presentation/d/1pjIKEgSanmNfROJDWEXxD9iExxVt3dLbvCN9J6Jpf7A/edit", type: "comparison" },
    ],
  },
  {
    name: "Innovaccer",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Population Health / VBC Data Platform",
    website: "https://innovaccer.com/",
    overview: "Innovaccer is a health data platform focused on population health management and value-based care analytics. Core product: unified patient data aggregation from EHRs, claims, and social determinants — presented through a care management and analytics layer. Strong in data aggregation and back-office analytics. Limited in point-of-care physician workflow. Sells to health systems, ACOs, and payers. Unicorn valuation (~$1.3B).",
    keyFacts: "– Founded: 2014 · HQ: San Francisco, CA\n– Funding: ~$375M raised · Valuation: ~$1.3B (unicorn)\n– ~1,000+ employees\n– Core: care management platform, population analytics, data aggregation (InData platform)\n– EHR integrations: Epic, Cerner, others — primarily data ingestion, limited bidirectional push\n– Workflow: back-office care teams, care managers, quality teams — not embedded in physician workflow\n– Customers: health systems, large physician groups, payers, ACOs\n– AI: predictive analytics, risk stratification, care gap identification",
    differentiation: "– Stops at back office — does not reach physician at point of care with actionable, evidence-linked suggestions\n– Data aggregation strength vs. Navina's clinical intelligence at point of care\n– Much lower physician specificity — not built for the physician encounter workflow\n– No ambient documentation\n– No prospective HCC at point of care\n– No independent clinical study on physician adoption or burnout\n– Navina reaches the moment of clinical decision; Innovaccer reaches the data warehouse",
    lastUpdated: "2025-06-07",
    sortOrder: 8,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Innovaccer-33931faa1fb780b8bb99c5e2f0ad23f2", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1CwYVWAwDnn7KL9QS41PddmpQC5QI97rPZ5Cn1WkfboA/edit", type: "overview" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1an3CUSNqebu8MIR0UvuVaVhCtLW5f6G9", type: "folder" },
      { label: "Demo Screenshots", url: "https://drive.google.com/drive/folders/1VlzSJOn5NESG8FE76F8ya-3k80Izh4TT", type: "screenshots" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1geWKT_-JaPz38Xi9DvnF8spdrWedlzAt/view", type: "summary" },
    ],
  },
  {
    name: "Persivia",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Risk Adjustment / Population Health",
    website: "https://persivia.com/",
    overview: "Persivia is a value-based care platform offering risk adjustment, care management, and population health analytics. Targets ACOs, health plans, and Medicare Advantage organizations. Provides both prospective and retrospective HCC workflows. Has care management module for complex patient outreach. Mid-market positioning with competitive pricing. Lower brand recognition than Innovaccer or Arcadia.",
    keyFacts: "– HQ: Woburn, MA\n– Core: risk adjustment (prospective + retrospective), care management, population analytics\n– Customers: ACOs, Medicare Advantage, health systems\n– Workflow: both point-of-care provider alerts and retrospective coding support\n– EHR integrations: Epic, Cerner, others\n– Mid-market pricing vs. enterprise competitors",
    differentiation: "– Limited unstructured data NLP vs. Navina's full-spectrum document ingestion\n– No ambient documentation\n– Limited physician engagement tools vs. Navina's EHR-native embedded workflow\n– No independent clinical studies\n– Smaller scale and brand recognition",
    lastUpdated: "2025-06-07",
    sortOrder: 9,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Persivia-30931faa1fb780c9a024f83df8e19fc9", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1L2gC7djpx_6r0Zk6IcYVo1g6NihH4pjO-G7NfByM6tA/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1wZJ33WNko6JKA2idPZX23CW62mWTxrxsqE8yxaV7dTY/edit", type: "battlecard" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1RkT1XKM3-yc--UWEE1guA7qRIjlHhHpV", type: "folder" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1VvARU7cXMXJelYPWBq90A8c8gVDsKUIl/view", type: "summary" },
    ],
  },
  {
    name: "Arcadia",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Population Health / VBC Data Platform",
    website: "https://arcadia.io/",
    overview: "Arcadia is a population health analytics and VBC enablement platform focused on aggregating multi-source clinical and claims data for ACOs, health systems, and payers. Core product: data aggregation, analytics, and care management workflows. Strong in large network analytics and ACO reporting. Limited in point-of-care physician engagement — primarily a back-office/analytics tool.",
    keyFacts: "– Founded: 2002 · HQ: Burlington, VT\n– Funding: ~$67M+ raised\n– ~400 employees\n– Core: data aggregation, population analytics, ACO reporting, quality/HEDIS tracking\n– Customers: ACOs, health systems, payers, government programs\n– EHR integrations: broad (Epic, Cerner, Athena, and many others)\n– Workflow: care management teams, quality teams, administrators — not physician-facing\n– No ambient documentation",
    differentiation: "– Back-office analytics vs. Navina's point-of-care clinical intelligence\n– No physician-facing workflow or embedded EHR experience\n– No ambient documentation\n– No prospective HCC at point of care\n– Strong data aggregation; Navina wins on clinical action at the point of care\n– Arcadia is an analytics/reporting platform; Navina is a clinician workflow tool",
    lastUpdated: "2025-06-07",
    sortOrder: 10,
    sources: [
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1PtZ8_Mcgyxj758uWuGUat9dqTboUIZt7", type: "folder" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1P2X1saQqH662tzAD0rfKv1ATu0NqlR9Y/view", type: "summary" },
      { label: "Demo Screenshots", url: "https://drive.google.com/drive/folders/12LtoalXIr-i7bWhGaefgNPkA60cmqlum", type: "screenshots" },
      { label: "Thought Leadership eBook", url: "https://drive.google.com/file/d/1Lt2LiyKM5Zd0UVBf_43xUEG_VK1OEd2A/view", type: "document" },
    ],
  },
  {
    name: "The Garage",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Population Health / VBC",
    website: "https://www.thegaragein.com/",
    overview: "The Garage is a value-based care enablement organization or platform. Limited public information available — verify current product details and market position via web search.",
    keyFacts: "– Category: value-based care / population health\n– Limited public information available — web search recommended for current details",
    differentiation: "– Verify current competitive details via web search",
    lastUpdated: "2025-06-07",
    sortOrder: 11,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/The-Garage-Bridge-33931faa1fb780789c4ee77e089d9332", type: "notion" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1wRLT01xNsV_gceCRrdJbAmkienWTp460", type: "folder" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1xWFAEazVTVLLx6JZBREiFQgnQBKAYZcM/view", type: "summary" },
      { label: "Pricing Proposal", url: "https://drive.google.com/file/d/1emyMEGe3s_CPDUPYQYNt9thXVj5tUqXk/view", type: "pricing" },
    ],
  },
  {
    name: "Health Catalyst",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Health Data Platform / Analytics",
    website: "https://www.healthcatalyst.com/",
    overview: "Health Catalyst (HCAT) is a publicly-traded health data platform company focused on data warehousing, analytics, and performance improvement programs for large health systems. Core product: Late-Binding Data Warehouse (EDW) with analytics applications on top. Strong in hospital operational analytics, quality improvement, and financial performance. Not designed for physician point-of-care workflows — primarily sells to health system IT and analytics teams.",
    keyFacts: "– Founded: 2008 · HQ: Salt Lake City, UT\n– Public company (HCAT, NASDAQ) · ~$260M annual revenue (~2024)\n– ~1,200 employees\n– Core: health data warehouse (Ignite platform), analytics apps, AI/ML modules\n– Customers: large health systems, academic medical centers, hospital networks\n– Products: data platform, care management suite, financial/quality analytics\n– No ambient documentation capability\n– Not focused on primary care VBC or physician point-of-care HCC workflows",
    differentiation: "– Enterprise data infrastructure vs. Navina's point-of-care clinical intelligence\n– Targets health system CIOs and data teams, not individual physicians\n– No prospective HCC at point of care\n– No ambient documentation\n– No care gap closure in the physician visit\n– Health Catalyst is a data warehouse play; Navina is a clinical action play at the bedside",
    lastUpdated: "2025-06-07",
    sortOrder: 12,
    sources: [
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1oRIUyYc3SNCgOin1FOfc0h_qTJW3nKnm/view", type: "summary" },
      { label: "Demo Screenshots", url: "https://drive.google.com/drive/folders/1wVS1-sA63ff2aQUzGJgguJw_0fhKA8PP", type: "screenshots" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1iWFFr51pH2eB9NlESOjIDjF8aKFWhh71", type: "folder" },
    ],
  },
  {
    name: "Lightbeam Health",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Population Health / Care Management",
    website: "https://lightbeamhealth.com/",
    overview: "Lightbeam Health Solutions is a population health management platform focused on care management, risk stratification, and care coordination for ACOs and physician groups. Provides care management workflows, patient outreach, and quality tracking. Acquired by Privia Health to support their VBC network. Primarily serves care teams and care managers — limited direct physician encounter workflow.",
    keyFacts: "– HQ: Nashville, TN\n– Acquired by Privia Health (~2021)\n– Core: care management, patient stratification, care coordination, quality tracking\n– Target: ACOs, physician groups, VBC networks (primarily Privia's own network)\n– Workflow: care managers and population health teams — not individual physician visit\n– No ambient documentation\n– No prospective HCC at point of care",
    differentiation: "– Care management platform vs. Navina's physician-facing clinical intelligence\n– Focuses on the care team (care managers, nurses), not the physician encounter\n– No prospective HCC at point of care\n– No ambient documentation\n– No unstructured data NLP\n– Now primarily an internal tool within the Privia Health ecosystem",
    lastUpdated: "2025-06-07",
    sortOrder: 13,
    sources: [
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1N3ewEE7YZp3-PNUXoQE8StkqdI5wBgGB", type: "folder" },
    ],
  },
  {
    name: "Azara Healthcare",
    category: "HCC / Risk Adj.",
    subgroup: "Pop Health",
    positioning: "Population Health / FQHC Analytics",
    website: "https://www.azarahealthcare.com/",
    overview: "Azara Healthcare is a population health analytics and quality reporting platform focused primarily on Federally Qualified Health Centers (FQHCs), community health centers, and safety-net organizations. Specializes in UDS reporting, HEDIS measures, and care gap tracking for government-funded health programs. Strong in the FQHC market — minimal overlap with commercial Medicare Advantage or primary care VBC.",
    keyFacts: "– HQ: Burlington, MA\n– Core: population health analytics, UDS reporting, HEDIS/quality tracking, care gap management\n– Primary market: FQHCs, community health centers, safety-net providers\n– Integrations: Epic, Cerner, eClinicalWorks, and FQHC-specific EHRs\n– Not focused on Medicare Advantage or commercial risk adjustment\n– No ambient documentation\n– No point-of-care HCC coding",
    differentiation: "– FQHC/safety-net focus vs. Navina's Medicare Advantage and primary care VBC market\n– Different market segment — minimal overlap with Navina's target buyers\n– No point-of-care HCC risk adjustment\n– No ambient documentation\n– Reporting/analytics tool vs. Navina's real-time clinical intelligence platform",
    lastUpdated: "2025-06-07",
    sortOrder: 14,
    sources: [
    ],
  },
  {
    name: "Abridge",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://www.abridge.com/",
    overview: "Abridge is an AI ambient documentation platform focused on converting physician-patient conversations into structured clinical notes. Key partnership with UPMC (health system) and deep Epic integration. Raised significant funding and positioned as a premium ambient scribe. Strong in academic medical centers and large health systems. Documentation-only platform — no HCC risk adjustment, no care gaps, no quality/HEDIS, no population health.",
    keyFacts: "– Founded: 2018 · HQ: Pittsburgh, PA\n– Funding: ~$450M+ raised (incl. $250M round Oct 2024, Spark Capital lead)\n– ~200 employees\n– Key partnerships: UPMC (anchor), Epic (deep integration in App Orchard)\n– Workflow: pre/during/post visit ambient capture → structured note → push to Epic\n– Specialties: broad (primary care, cardiology, oncology, etc.)\n– Pricing: per-seat subscription, enterprise deals\n– Note ready time: near real-time\n– No HCC coding / no risk adjustment / no care gaps / no quality module",
    differentiation: "– Documentation only vs. Navina's full VBC platform (ambient + HCC + quality + analytics)\n– No prospective HCC at point of care — purely a transcription/documentation tool\n– No care gap identification or quality workflows\n– No unstructured data NLP across historical records — captures only current visit\n– Navina: ambient + evidence-backed HCC suspecting + quality = 3 revenue streams\n– Abridge replaces the scribe; Navina replaces the chart review + scribe + coding team\n– Abridge UPMC/Epic dependency vs. Navina's EHR-agnostic approach",
    lastUpdated: "2025-06-07",
    sortOrder: 15,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Abridge-27e31faa1fb780078eeecfff9abc7c37", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1rd8GWpVmjF32Og0oob42JDxo9eb4pOYfkGeHp-z20Qk/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1OgxDQxP1hMZuHc9ATH-BO1xU3ciSn1pfsJGaUnP68Z4/edit", type: "battlecard" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1hka1NsU6moYsfImGU7bL-YU-MVZmTKYj", type: "folder" },
    ],
  },
  {
    name: "Ambience Healthcare",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://www.ambiencehealthcare.com/",
    overview: "Ambience Healthcare is an enterprise ambient AI documentation platform targeting large health systems. Focuses on real-time clinical note generation during patient encounters. Strong in complex specialties. Received investment from OpenAI and positions itself as an AI-native clinical documentation solution. Documentation-only — no HCC coding, no risk adjustment, no quality/HEDIS.",
    keyFacts: "– Founded: 2020 · HQ: San Francisco, CA\n– Funding: ~$100M+ raised (OpenAI investment)\n– Core: enterprise ambient documentation, specialty coverage\n– Workflow: real-time ambient capture → specialty-specific structured notes\n– Target: large health systems, academic medical centers\n– Notable investors: OpenAI, Kleiner Perkins\n– No HCC / no risk adjustment / no quality module",
    differentiation: "– Documentation only — no HCC, no risk adjustment, no quality\n– Enterprise-only motion (large health systems) vs. Navina's primary care + VBC focus\n– OpenAI backing adds AI credibility but not clinical outcome evidence\n– No independent clinical studies on physician adoption or outcomes\n– Navina delivers ambient + HCC + quality in one platform",
    lastUpdated: "2025-06-07",
    sortOrder: 16,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Ambience-AI-28631faa1fb78029b3c6da5ef1d23c25", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1WlKDGPBZO9u7lrOp53t-rANFdGu98dfjfHMItNX7New/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1r1I8oDdFoMWXhva73OGWM3lEgRWdz4xuwr46uElGHgk/edit", type: "battlecard" },
    ],
  },
  {
    name: "Suki",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Voice Assistant",
    website: "https://www.suki.ai/",
    overview: "Suki is a voice-powered AI clinical assistant and ambient documentation platform. Offers both ambient note generation and a conversational voice interface for EHR navigation and clinical queries. Google-backed. Targets physician groups, health systems, and EHR vendors via white-label partnerships. Documentation and voice navigation only — no HCC risk adjustment, no care gaps, no quality/HEDIS.",
    keyFacts: "– Founded: 2017 · HQ: Redwood City, CA\n– Funding: ~$165M raised (Google investment)\n– Core: ambient documentation + voice assistant for EHR interaction\n– Integrations: Epic, Cerner, Athena, eClinicalWorks, and others\n– White-label partnerships with EHR vendors\n– Pricing: per-seat subscription\n– No HCC / no risk adjustment / no quality module",
    differentiation: "– Voice/documentation tool vs. Navina's full VBC platform\n– No HCC coding or risk adjustment\n– No care gap or quality workflows\n– Google backing brings distribution but not clinical depth\n– EHR white-label strategy means limited brand in direct sales\n– Navina uses ambient as one component of a broader clinical intelligence platform",
    lastUpdated: "2025-06-07",
    sortOrder: 17,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Suki-AI-28e31faa1fb780b98e6dee2bf3d9b33d", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1D8lLcPP4dB9xykrvomRPm8rcppGm9KTDnWGnyWORPXI/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1OgxDQxP1hMZuHc9ATH-BO1xU3ciSn1pfsJGaUnP68Z4/edit", type: "battlecard" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1qn09suUl9ON9C-VqbpgDH5YFR-N4q3CB", type: "folder" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1KyLVcAJjy1wUkWm_bCm-sCSu2-aAVnuL/view", type: "summary" },
      { label: "Pricing PDF", url: "https://drive.google.com/file/d/1clb0EVl2FYCI0KfoPjArSWyhPYDiArG9/view", type: "pricing" },
      { label: "Pricing Meeting Summary", url: "https://drive.google.com/file/d/1JoljmfhixgHUa27oMgLmrplgHgqsOAC6/view", type: "pricing" },
    ],
  },
  {
    name: "Nuance DAX",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation (Microsoft)",
    website: "https://www.microsoft.com/en-us/health-solutions/clinical-workflow/dragon-copilot",
    overview: "Nuance DAX (Dragon Ambient eXperience) is Microsoft's ambient clinical intelligence product, evolved from Dragon Medical dictation. Market leader in clinical documentation by scale. Deep Epic integration. Now rebranded as Microsoft Dragon Copilot, integrating Azure AI and Teams. Sells to large health systems and integrated delivery networks. Documentation-focused — limited in VBC-specific workflows like HCC coding or quality gap closure.",
    keyFacts: "– Owner: Microsoft (acquired Nuance for $19.7B in 2021)\n– Product: Dragon Copilot (formerly DAX Copilot / DAX Express)\n– Scale: largest ambient documentation footprint in US healthcare\n– Integration: Epic (deep), Cerner, others\n– Distribution: Microsoft enterprise sales + direct\n– Pricing: enterprise, large health system contracts\n– AI: Azure OpenAI-powered\n– No dedicated HCC risk adjustment module\n– No care gap / quality / population health capability",
    differentiation: "– Documentation giant vs. purpose-built VBC platform\n– Microsoft scale but healthcare-specific depth is limited\n– No prospective HCC at point of care\n– No care gap or quality workflows\n– Sells to large health systems; Navina focuses on VBC-aligned primary care groups/ACOs\n– Navina's independence vs. Microsoft's bundling with Teams/Azure = different buyer motion\n– No independent clinical studies on physician outcome improvement",
    lastUpdated: "2025-06-07",
    sortOrder: 18,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Nuance-Dax-Copilot-29231faa1fb78037bd36c2442bbf3af2", type: "notion" },
      { label: "Ambient Main Deck", url: "https://docs.google.com/presentation/d/1r8B7iWXxn0a7N31a7shLTJWU6jjx9dyorzMsLzM8QoQ/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1OgxDQxP1hMZuHc9ATH-BO1xU3ciSn1pfsJGaUnP68Z4/edit", type: "battlecard" },
    ],
  },
  {
    name: "Nabla",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://www.nabla.com/",
    overview: "Nabla is a French AI ambient documentation startup expanding aggressively in the US market. Core product: real-time ambient note generation during physician-patient encounters. Known for a clean UX and a developer-facing API (Nabla API) used to embed ambient documentation into existing health platforms. Supports multiple specialties. Documentation-only — no HCC coding, no risk adjustment, no quality/HEDIS.",
    keyFacts: "– Founded: 2018 · HQ: Paris, France (US expansion)\n– Funding: ~$30M+ raised\n– Core: ambient documentation, specialty-specific note templates, developer API\n– Integrations: multiple EHRs via FHIR API\n– API-first strategy: enables embedding in third-party platforms\n– Target: physician groups, health systems, platform builders\n– No HCC / no risk adjustment / no quality module",
    differentiation: "– Documentation only vs. Navina's full VBC platform\n– French company entering US — less brand equity in US enterprise healthcare\n– No HCC or risk adjustment capability\n– API-first may commoditize ambient scribing vs. Navina's integrated platform depth\n– No clinical outcome validation studies in US market",
    lastUpdated: "2025-06-07",
    sortOrder: 19,
    sources: [
      { label: "Ambient Main Deck", url: "https://docs.google.com/presentation/d/1r8B7iWXxn0a7N31a7shLTJWU6jjx9dyorzMsLzM8QoQ/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1OgxDQxP1hMZuHc9ATH-BO1xU3ciSn1pfsJGaUnP68Z4/edit", type: "battlecard" },
    ],
  },
  {
    name: "Heidi",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://www.heidihealth.com/",
    overview: "Heidi Health is an Australian AI ambient medical scribe platform expanding globally. Core product: real-time ambient note generation for general practice and primary care, known for ease of use and fast self-serve onboarding. Consumer-friendly pricing ($99–149/month) makes it popular with solo physicians and small practices. Documentation-only — no HCC coding, no risk adjustment, no quality workflows. Limited US enterprise presence.",
    keyFacts: "– Founded: 2021 · HQ: Melbourne, Australia (expanding to US/UK)\n– Funding: ~$10M+ raised\n– Core: ambient documentation for general practice, primary care\n– Target: solo physicians, small practices, general practitioners\n– Pricing: freemium + low monthly subscription\n– No EHR deep integration — primarily copy-paste workflow\n– No HCC / no risk adjustment / no quality module",
    differentiation: "– Consumer/SMB tool vs. Navina's enterprise VBC platform\n– No HCC or risk adjustment capability\n– Australian focus vs. Navina's US Medicare Advantage expertise\n– No enterprise EHR integration or bidirectional data push\n– No US clinical validation studies\n– Competes on price/simplicity for tiny practices; Navina competes in enterprise ACOs and health systems",
    lastUpdated: "2025-06-07",
    sortOrder: 20,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Heidi-Health-29931faa1fb7803a813ed9531ca63707", type: "notion" },
      { label: "Demo Summary", url: "https://drive.google.com/file/d/1YOjyn6oOnrJUDjPViYWhDCLX7L0y_Bxj/view", type: "summary" },
      { label: "Initial Call Summary", url: "https://drive.google.com/file/d/1mY-sHvwcplhMnBeTJ7Maz9PbQQ8U678s/view", type: "document" },
    ],
  },
  {
    name: "Marvix AI",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://www.marvix.ai/",
    overview: "Marvix AI is an ambient clinical documentation platform. Early stage with limited public information — verify current product details, funding, and customers via web search.",
    keyFacts: "– Focus: ambient clinical documentation\n– Stage: early stage\n– Limited public information — web search recommended",
    differentiation: "– Documentation-focused vs. Navina's full VBC platform\n– No confirmed HCC or risk adjustment capability\n– Verify current details via web search",
    lastUpdated: "2025-06-07",
    sortOrder: 21,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Marvix-AI-32631faa1fb78042881beb96468fb5d0", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1L9JaVIyCPJ6ZTGADCRKaIqArsdaBKJU97BEtQxykzZo/edit", type: "overview" },
    ],
  },
  {
    name: "Freed AI",
    category: "HCC / Risk Adj.",
    subgroup: "Ambient Scribes",
    positioning: "Ambient AI / Clinical Documentation",
    website: "https://freed.ai/",
    overview: "Freed AI is a consumer-facing AI medical scribe focused on individual physicians and small practices. Core product: ambient note generation via browser or smartphone app. Known for the lowest price point in the market and instant self-serve onboarding — no sales team, no implementation. Targets solo practitioners and small groups, not enterprise health systems. Documentation-only — no HCC coding, no risk adjustment, no quality/HEDIS.",
    keyFacts: "– Founded: 2023 · HQ: US\n– Funding: seed stage (~$2M+)\n– Core: ambient note generation via browser/iOS app\n– Target: individual physicians, solo practices, small groups\n– Pricing: ~$99–149/month per physician (self-serve, no contract)\n– No deep EHR integration — copy-paste workflow\n– No HCC / no risk adjustment / no quality module\n– No enterprise sales team or customer success",
    differentiation: "– Solo/consumer tool vs. Navina's enterprise VBC platform\n– No EHR integration depth (copy-paste vs. Navina's bidirectional push)\n– No HCC or risk adjustment capability\n– No care gap or quality workflows\n– No enterprise implementation or support\n– Competes on simplicity and price in tiny practices; Navina competes in enterprise ACOs",
    lastUpdated: "2025-06-07",
    sortOrder: 22,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Freed-AI-29531faa1fb780dbb17bf4e0d273d317", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1QgHi1aObL5Xc-frkYhWK1FPbtJXpMlhtXTK6pnGmbZk/edit", type: "overview" },
    ],
  },
  {
    name: "Epic Systems",
    category: "EHRs",
    subgroup: null,
    positioning: "EHR Platform / Clinical Decision Support",
    website: "https://www.epic.com/",
    overview: "Epic Systems is the dominant EHR vendor in the US, serving large health systems, academic medical centers, and integrated delivery networks. Offers native clinical decision support (CDS) tools including BPA (Best Practice Advisories) and Cosmos data network. Has its own ambient documentation module (Aura/NoteReader) and is building AI features. Navina competes as an overlay/partner — providing deeper HCC specificity, unstructured data NLP, and independent clinical validation that Epic's native tools lack.",
    keyFacts: "– Founded: 1979 · HQ: Verona, WI\n– Private company · Estimated revenue: ~$4–5B/year\n– ~12,000 employees\n– Market share: ~35–40% of US hospital beds\n– EHR: dominant in large health systems, academic medical centers\n– CDS: BPA alerts — but high alert fatigue, low follow rates reported\n– Ambient: Epic Aura + NoteReader (basic) + DAX Copilot partnership\n– AI: Cosmos data + AI predictive tools (Sepsis, deterioration, readmission)\n– Navina is an Epic App Orchard partner",
    differentiation: "– Epic BPA alert fatigue: reported follow rates 20–50% vs. Navina 90% address rate\n– Epic CDS: primarily structured data, limited unstructured NLP\n– Epic's HCC tools: recapture-focused, not suspecting new conditions\n– Epic builds horizontal — Navina built specifically for VBC/HCC specificity\n– Navina adds value ON TOP of Epic, not competing with core EHR functionality\n– Independent PHYX/AAFP studies validate Navina in Epic-native workflows\n– Epic's ambient (DAX partnership) is documentation only — no HCC, no care gaps",
    lastUpdated: "2025-06-07",
    sortOrder: 23,
    sources: [
      { label: "Epic — Main Deck", url: "https://docs.google.com/presentation/d/17ieKC-yWV69_5B6ixli1YheydnjNGztN-9GEDtGa-_o/edit?slide=id.g3e083810991_2_2#slide=id.g3e083810991_2_2", type: "overview" },
      { label: "Navina vs EHRs — Comparison", url: "https://docs.google.com/presentation/d/1m57r1km7R-qQZyf_stHJYgo6cO5QhqbGWkWghWoXEEs/edit?slide=id.g3ea77f2c691_0_396#slide=id.g3ea77f2c691_0_396", type: "battlecard" },
      { label: "Discovery Questions for EHRs (Epic)", url: "https://docs.google.com/presentation/d/1MjJ1md-Vugb7X5hcpVmXzO0GWzE3OngeYU1-pseOf0A/edit?slide=id.g3ea784d216d_0_79#slide=id.g3ea784d216d_0_79", type: "document" },
      { label: "Epic & Stanson — New OPA and CDI Functionality", url: "https://drive.google.com/file/d/1j4Kcsg3IFGpFO_2aS3dzetR8DVrIYAIA/view", type: "document" },
      { label: "Epic — Main Notion Page", url: "https://www.notion.so/navinaai/EPIC-35d31faa1fb780e9818acc4c27fa3615", type: "notion" },
      { label: "Epic — Main Drive Folder", url: "https://drive.google.com/drive/u/0/folders/1rF2pLa7ULuAG2Ex-slbbL8dNL1poicHD", type: "folder" },
    ],
  },
  {
    name: "Athenahealth",
    category: "EHRs",
    subgroup: null,
    positioning: "EHR Platform / Ambulatory",
    website: "https://www.athenahealth.com/",
    overview: "Athenahealth (Athena Health Group, owned by Veritas Capital) is a cloud-based EHR, practice management, and patient engagement platform dominant in ambulatory and independent physician practice settings. Serves ~160,000 providers. Known for cloud-native architecture and integrated revenue cycle management. Has native care gap and HEDIS reporting tools and is building AI features (athenaOne AI). Navina integrates with athenahealth — overlaying HCC and quality intelligence on top of its workflow.",
    keyFacts: "– Founded: 1997 · HQ: Watertown, MA\n– Owner: Veritas Capital (private equity) — merged with Virence Health (GE Healthcare IT)\n– ~5,000–6,000 employees · ~160,000 providers on platform\n– Core: cloud EHR (athenaOne), practice management, revenue cycle, patient engagement\n– Market: ambulatory care, independent practices, specialty groups, FQHCs\n– Quality: native care gap and HEDIS reporting (basic)\n– AI: athenaOne AI (ambient notes, workflow automation — building out)\n– No dedicated HCC risk adjustment for Medicare Advantage populations",
    differentiation: "– Navina overlays ON TOP of athenahealth — not a head-to-head EHR competition\n– athenahealth's native care gap tools are basic vs. Navina's evidence-backed, real-time HCC closure\n– athenahealth processes structured data only; Navina adds NLP on unstructured records\n– athenahealth's ambient AI is documentation-only; Navina adds HCC + quality layer\n– Navina's 77% acceptance rate vs. lower follow rates from athena's native alerts\n– Large athena practice base = major Navina integration opportunity (especially as those practices join MA/ACO contracts)",
    lastUpdated: "2025-06-07",
    sortOrder: 24,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Athenahealth-34b31faa1fb78023ade5d822c1d8e34f", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1xfF6nMnxFD39JmfuuSWmyTN4atmoSW2aLB8a04JtMsY/edit", type: "overview" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1nTEmrqTEgaNk5Fl4Vrc2QT1E2YJV02fy", type: "folder" },
      { label: "Future Releases Dec 2025", url: "https://docs.google.com/document/d/1AvDbtKcIszuiuKvxCMF-ErGZPlmoaRAOOBZ1e4o2ZPM/edit", type: "document" },
    ],
  },
  {
    name: "eClinicalWorks",
    category: "EHRs",
    subgroup: null,
    positioning: "EHR Platform / Ambulatory",
    website: "https://www.eclinicalworks.com/",
    overview: "eClinicalWorks (eCW) is one of the largest US ambulatory EHR vendors, serving ~180,000 providers across 150,000 facilities. Known for cost-competitive pricing targeting small and mid-size practices. Had a $155M DOJ settlement in 2017 for misrepresenting EHR certification. Has a population health module (PHM Suite) and basic care gap tools. Building AI features (Eva AI assistant). Navina integrates with eCW, adding a clinical intelligence layer on top.",
    keyFacts: "– Founded: 1999 · HQ: Westborough, MA\n– Private · ~5,000 employees\n– Scale: ~180,000 providers, 150,000 facilities\n– Core: ambulatory EHR, practice management, patient engagement\n– PHM Suite: care management, care gaps, quality reporting (basic)\n– AI: Eva (EHR navigation and note generation assistant)\n– 2017: $155M DOJ settlement for misrepresenting EHR certification\n– Heavy use in independent/small practices, FQHCs, community health centers\n– No dedicated HCC risk adjustment for MA populations",
    differentiation: "– Navina overlays ON TOP of eCW — not direct EHR competition\n– eCW's native care gap tools are basic vs. Navina's evidence-backed, real-time HCC workflow\n– eCW 2017 DOJ fraud settlement creates trust concerns in compliance-sensitive organizations\n– eCW processes structured data; Navina adds unstructured NLP across all record types\n– Large eCW practice base = Navina integration and sales opportunity\n– eCW's Eva is EHR navigation/documentation — not HCC-specific or prospective",
    lastUpdated: "2025-06-07",
    sortOrder: 25,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/eClinicalWorks-35c31faa1fb7801fa550efa21c083730", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1I4l53I0uoOMh8hRyuej5x9lfKQadGej9nYvkAy3--qc/edit", type: "overview" },
      { label: "Comparison", url: "https://docs.google.com/presentation/d/1QEvD0ixBNFBjbN1C1sYemirmXjIm2UrrKen6kmFPJYc/edit", type: "battlecard" },
      { label: "Drive Folder", url: "https://drive.google.com/drive/folders/1OTCVhQRe5aIiYswYtBk89RkG5lt6rDx2", type: "folder" },
    ],
  },
  {
    name: "Raapid",
    category: "Payer Solutions",
    subgroup: null,
    positioning: "Risk Adjustment / Payer Solutions",
    website: "https://www.raapidinc.com/",
    overview: "Raapid is a risk adjustment platform targeting health plans and Medicare Advantage payers. Focuses on retrospective HCC coding, chart review automation, and risk adjustment analytics for payers. Primarily a back-office tool for health plan risk adjustment operations — no point-of-care physician workflow.",
    keyFacts: "– Focus: retrospective HCC chart review and risk adjustment for payers\n– Target: health plans, Medicare Advantage organizations\n– Workflow: retrospective, payer-side operations\n– No physician-facing point-of-care interface\n– No ambient documentation\n– Limited public information on funding and scale",
    differentiation: "– Payer-focused back-office tool vs. Navina's provider-first point-of-care platform\n– Retrospective workflow vs. Navina's prospective real-time HCC suspecting\n– No physician-facing interface\n– No ambient documentation\n– No quality/HEDIS module",
    lastUpdated: "2025-06-07",
    sortOrder: 26,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Raapid-35f31faa1fb780059808dbfe97f97d68", type: "notion" },
      { label: "Initial Discovery Transcript", url: "https://drive.google.com/file/d/1KM6By2k5IQXjCDLhHcrSJ_YPG5m41DzS/view", type: "document" },
      { label: "Initial Discovery Summary (V2)", url: "https://docs.google.com/document/d/1Ith5BjC9WQA7FJY0SGpHBIDPVfZ6gbx_MqKCdK5Zc0M/edit", type: "document" },
    ],
  },
  {
    name: "Vertexa Health",
    category: "Payer Solutions",
    subgroup: null,
    positioning: "Risk Adjustment / Payer Solutions",
    website: "https://www.vertexahealth.com/",
    overview: "Vertexa Health is a healthcare analytics and risk adjustment platform focused on payer-side solutions for Medicare Advantage and value-based care. Limited public information available — verify current product depth, customers, and market position via web search.",
    keyFacts: "– Focus: payer analytics, risk adjustment, Medicare Advantage\n– Limited public information — web search recommended for current details",
    differentiation: "– Payer-focused analytics vs. Navina's provider-first platform\n– Verify current competitive details via web search",
    lastUpdated: "2025-06-07",
    sortOrder: 27,
    sources: [
    ],
  },
  {
    name: "Pareto Intelligence",
    category: "Payer Solutions",
    subgroup: null,
    positioning: "Risk Adjustment / Payer Analytics",
    website: "https://paretointel.com/",
    overview: "Pareto Intelligence is a healthcare analytics company providing risk adjustment and quality performance analytics for health plans and Medicare Advantage organizations. Focuses on data-driven risk adjustment accuracy, quality measure tracking, and compliance analytics. Acquired by Cognizant (major IT services company), giving it enterprise distribution but reducing agility as an independent product.",
    keyFacts: "– HQ: Chicago, IL\n– Acquired by Cognizant (global IT services company)\n– Core: risk adjustment analytics, quality performance, HCC analytics for payers\n– Target: health plans, Medicare Advantage payers\n– Workflow: back-office payer analytics and compliance reporting\n– No provider-facing workflow\n– No ambient documentation",
    differentiation: "– Payer analytics tool vs. Navina's provider-facing clinical intelligence\n– Back-office analytics vs. real-time point-of-care workflow\n– No physician-facing interface\n– No ambient documentation\n– Navina creates the clinical signal (at point of care); Pareto analyzes risk data after the fact\n– Cognizant acquisition may slow product innovation",
    lastUpdated: "2025-06-07",
    sortOrder: 28,
    sources: [
      { label: "Notion Page", url: "https://app.notion.com/p/navinaai/Pareto-Intelligence-37531faa1fb780cbad98c3c6a45c98d1", type: "notion" },
      { label: "Overview May 2026 (PDF)", url: "https://drive.google.com/file/d/1f5inNIJpRVfs0c6nzwHkpHWIM9AKfE2T/view", type: "document" },
    ],
  },
  {
    name: "Cotiviti",
    category: "Payer Solutions",
    subgroup: null,
    positioning: "Risk Adjustment / Payer Analytics",
    website: "https://www.cotiviti.com/",
    overview: "Cotiviti is a leading healthcare analytics company providing data-driven solutions for health plans, primarily focused on risk adjustment, quality improvement (HEDIS/Stars), and payment integrity. Serves most major US health plans and Medicare Advantage payers. Acquired from Verisk Health by Veritas Capital in 2018. Strong in large-scale retrospective chart review and payer analytics operations.",
    keyFacts: "– HQ: South Jordan, UT (offices nationwide)\n– Owner: Veritas Capital (private equity)\n– Scale: serves most major US health plans and MA payers\n– Core: risk adjustment (retrospective HCC), HEDIS/Stars quality analytics, payment integrity, consumer engagement\n– Model: services + software platform for payer operations\n– No physician-facing point-of-care workflow\n– No ambient documentation",
    differentiation: "– Payer back-office operations vs. Navina's physician-first point-of-care platform\n– Retrospective chart review vs. Navina's prospective real-time HCC suspecting at the visit\n– No physician-facing EHR-embedded interface\n– No ambient documentation\n– Navina creates the clinical signal at the physician encounter; Cotiviti processes charts after the fact",
    lastUpdated: "2026-06-08",
    sortOrder: 29,
    sources: [
      { label: "Notion Page", url: "https://app.notion.com/p/navinaai/Cotiviti-37531faa1fb780d88dd7cb889038668c", type: "notion" },
    ],
  },
  {
    name: "GeBBS",
    category: "Payer Solutions",
    subgroup: null,
    positioning: "Healthcare Outsourcing / Revenue Cycle",
    website: "https://gebbs.com/",
    overview: "GeBBS Healthcare Solutions is a healthcare outsourcing company specializing in revenue cycle management, medical coding, and clinical documentation improvement (CDI) services. Provides both technology and human coding staff for HCC risk adjustment. Primarily a services/BPO company rather than a software platform. Targets health plans, hospitals, and physician groups for outsourced coding and risk adjustment operations.",
    keyFacts: "– HQ: Los Angeles, CA\n– Private equity-backed\n– Core: revenue cycle outsourcing, medical coding, CDI, risk adjustment services\n– Model: services (human coders + offshore) + technology platform\n– Target: hospitals, health systems, health plans, physician groups\n– HCC: retrospective chart review with human coder teams + AI assist\n– No physician-facing workflow tool\n– No ambient documentation",
    differentiation: "– Outsourced services model vs. Navina's SaaS software platform\n– Human-coded retrospective vs. Navina's AI-driven prospective point-of-care\n– Labor-intensive model creates cost and scalability limits vs. Navina's scalable SaaS\n– No physician workflow or EHR integration\n– Navina reduces the need for outsourced coding by improving physician capture rate at the source",
    lastUpdated: "2025-06-07",
    sortOrder: 30,
    sources: [
    ],
  },
  {
    name: "Fold Health",
    category: "Other",
    subgroup: null,
    positioning: "Population Health / VBC Enablement",
    website: "https://www.fold.health/",
    overview: "Fold Health is a VBC enablement platform designed to help independent physician groups manage value-based care contracts. Provides analytics dashboards, care management workflows, and contract performance monitoring. Early-stage company targeting independent physician groups and ACOs looking to operationalize VBC contracts.",
    keyFacts: "– Stage: early stage / growth\n– Focus: VBC contract enablement, care gap management, quality performance tracking\n– Target: independent physician groups, ACOs\n– No ambient documentation\n– No dedicated HCC risk adjustment module\n– Limited public information on funding and scale",
    differentiation: "– VBC contract analytics vs. Navina's point-of-care clinical intelligence\n– No physician-facing workflow at point of care\n– No ambient documentation\n– No prospective HCC coding\n– Different layer of the VBC stack: contract management vs. clinical execution",
    lastUpdated: "2025-06-07",
    sortOrder: 31,
    sources: [
      { label: "Notion Page", url: "https://app.notion.com/p/navinaai/Fold-health-37431faa1fb780b798deec68bd2397ac", type: "notion" },
      { label: "Executive Summary", url: "https://docs.google.com/document/d/1h1AU8H2g9BbOKhHuj-MHPzjUm8oDUf3A35B1BJDRP10/edit", type: "document" },
      { label: "Navina vs Charta/Fold/MedChartScan (slides 1, 3)", url: "https://docs.google.com/presentation/d/1pjIKEgSanmNfROJDWEXxD9iExxVt3dLbvCN9J6Jpf7A/edit", type: "comparison" },
    ],
  },
  {
    name: "Zus Health",
    category: "Other",
    subgroup: null,
    positioning: "Health Data Network / FHIR Infrastructure",
    website: "https://zushealth.com/",
    overview: null,
    keyFacts: null,
    differentiation: null,
    lastUpdated: "2025-06-09",
    sortOrder: 32,
    sources: [
      { label: "Zus Health — Main Notion Page", url: "https://app.notion.com/p/navinaai/Zus-Health-37a31faa1fb780f59c5af420e7ae1fa4", type: "notion" },
    ],
  },
  {
    name: "Doximity",
    category: "Other",
    subgroup: null,
    positioning: "Physician Network / Communications / AI Tools",
    website: "https://www.doximity.com/",
    overview: "Doximity is the largest professional network for US physicians, with ~80% of US doctors as members (~2M+ clinicians). Core products: secure messaging, telehealth (Doximity Dialer), digital fax, and a medical newsfeed. Recently launched Doximity GPT — AI tools for clinical note drafting, letter writing, and patient communication. Generates revenue primarily through pharma/medtech marketing and talent placement. Not a clinical intelligence or risk adjustment platform — but has unmatched physician reach.",
    keyFacts: "– Founded: 2010 · HQ: San Francisco, CA\n– Public company (DOCS, NYSE) · ~$420M annual revenue (~2024)\n– ~900 employees\n– Members: ~2M+ US physicians and NPs (~80% of all US physicians)\n– Core: secure messaging, telehealth, e-fax, news feed\n– AI: Doximity GPT for note drafting, letters, patient communication\n– Revenue model: pharma/medtech advertising, talent placement — NOT direct provider SaaS\n– No HCC risk adjustment / no EHR bidirectional integration / no quality analytics",
    differentiation: "– Physician communications network vs. Navina's clinical intelligence platform\n– No HCC, no risk adjustment, no quality/HEDIS capability\n– No EHR bidirectional integration\n– Doximity GPT is note assistance only — not evidence-backed HCC suspecting\n– Revenue from pharma, not from VBC operators — very different buyer motion\n– Significant physician reach could be an awareness or co-marketing opportunity for Navina",
    lastUpdated: "2025-06-07",
    sortOrder: 33,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Doximity-36331faa1fb78097887de22863a9e109", type: "notion" },
      { label: "Company Overview Deck", url: "https://docs.google.com/presentation/d/1wrZj6PMt_28sCVILwhPD-MGsSXdMiWZD4h3tTvjFEF0/edit", type: "overview" },
    ],
  },
  {
    name: "Notable Health",
    category: "Other",
    subgroup: null,
    positioning: "Patient Intake / AI Automation",
    website: "https://www.notablehealth.com/",
    overview: "Notable Health is an AI-powered patient intake, care gap outreach, and administrative workflow automation platform. Core product: automated pre-visit patient intake via digital forms and text-based outreach, care gap closure through patient-facing engagement, and administrative task automation. Focuses on reducing front-desk burden and improving patient experience. Limited in physician-facing clinical intelligence or HCC risk adjustment.",
    keyFacts: "– Founded: 2017 · HQ: San Mateo, CA\n– Funding: ~$100M+ raised (Series B)\n– Core: AI-driven patient intake, care gap outreach to patients, admin workflow automation\n– Integrations: Epic, Cerner, athenahealth, eClinicalWorks\n– Target: health systems, physician groups, multi-specialty practices\n– Care gaps: patient-facing outreach and questionnaires — not physician CDS\n– No ambient documentation\n– No HCC risk adjustment or prospective coding",
    differentiation: "– Patient-facing automation vs. Navina's physician-facing point-of-care intelligence\n– Notable touches the front desk and patient; Navina touches the physician\n– No HCC risk adjustment or prospective coding\n– No ambient documentation\n– No unstructured data NLP across clinical records\n– Potential partner: Notable improves pre-visit intake data quality that Navina can then act on at the visit",
    lastUpdated: "2025-06-07",
    sortOrder: 34,
    sources: [
    ],
  },
  {
    name: "Eclat / Evarie",
    category: "Other",
    subgroup: null,
    positioning: "Risk Adjustment / Coding",
    website: "https://evaire.com/",
    overview: "ELCAT is a risk adjustment and HCC coding platform. Limited public information available — verify current product details, market position, and customers via web search.",
    keyFacts: "– Focus: risk adjustment, HCC coding\n– Limited public information available — web search recommended",
    differentiation: "– Verify current competitive details via web search\n– Likely retrospective coding workflow vs. Navina's prospective point-of-care approach",
    lastUpdated: "2025-06-07",
    sortOrder: 35,
    sources: [
      { label: "Notion Page", url: "https://www.notion.so/navinaai/Eclat-Evarie-36431faa1fb78040b0d5fe58cd33b803", type: "notion" },
    ],
  },
];
