import { PrismaClient } from "@prisma/client";
import { createHash } from "crypto";

const prisma = new PrismaClient();

function hashId(prefix: string, content: string): string {
  return `${prefix}-${createHash("md5").update(content).digest("hex").slice(0, 24)}`;
}

function mapProductArea(raw: string): string {
  const map: Record<string, string> = {
    "pop health": "POP_HEALTH",
    "quality": "QUALITY",
    "analytics": "ANALYTICS",
    "agentic": "AGENTIC",
    "agentic / pop health": "AGENTIC",
    "risk / dx": "RISK_DX",
    "risk/dx": "RISK_DX",
    "ambient": "AMBIENT",
    "general": "GENERAL",
    "competitive": "COMPETITIVE",
    "general / payer": "GENERAL",
    "general / onboarding": "GENERAL",
    "quality / data": "QUALITY",
    "copilot / ambient": "AMBIENT",
    "pop health / analytics": "POP_HEALTH",
    "analytics / pop health": "ANALYTICS",
  };
  return map[raw.toLowerCase().trim()] ?? "GENERAL";
}

function mapTheme(raw: string): string {
  const map: Record<string, string> = {
    "workflow": "WORKFLOW",
    "data / integration": "DATA_INTEGRATION",
    "data/integration": "DATA_INTEGRATION",
    "trust": "TRUST",
    "pain points": "PAIN_POINTS",
    "other pain points": "PAIN_POINTS",
    "goals": "GOALS",
    "pricing / wtp": "PRICING_WTP",
    "pricing/wtp": "PRICING_WTP",
    "agentic": "AGENTIC",
    "ui / labels": "OTHER",
    "ui / sections": "OTHER",
    "pilot feedback": "PILOT_FEEDBACK",
    "product feedback": "PRODUCT_FEEDBACK",
    "onsite visit": "ONSITE_VISIT",
    "feedback": "FEEDBACK",
    "adoption": "ADOPTION",
    "ongoing feedback": "ONGOING_FEEDBACK",
    "patient-based": "OTHER",
    "general": "OTHER",
    "companion codes": "OTHER",
    "grouping": "OTHER",
    "auto-doc": "OTHER",
    "auto-doc style": "OTHER",
    "clinical summary tab": "OTHER",
    "suggesting logic": "OTHER",
    "condition-based vs task-based": "OTHER",
    "hcc / risk": "OTHER",
    "icd / dropdown": "OTHER",
    "bulk actions / icd": "OTHER",
    "bulk actions": "OTHER",
    "analytics": "OTHER",
  };
  return map[raw.toLowerCase().trim()] ?? "OTHER";
}

function parseDate(raw: string): Date | null {
  if (!raw?.trim()) return null;
  const cleaned = raw.trim();
  const monthYear = cleaned.match(/^(\w{3})\s+(\d{4})$/);
  if (monthYear) return new Date(`${monthYear[1]} 1 ${monthYear[2]}`);
  const yearOnly = cleaned.match(/^(\d{4})$/);
  if (yearOnly) return new Date(`Jan 1 ${yearOnly[1]}`);
  const rangeYear = cleaned.match(/(\d{4})/);
  if (rangeYear) return new Date(`Jan 1 ${rangeYear[1]}`);
  try { return new Date(cleaned); } catch { return null; }
}

// [productArea, theme, persona, question, notesIntent, source]
const DISCOVERY_QUESTIONS: string[][] = [
  ["Pop Health", "Workflow", "Care Coordinator / Admin", "Walk me through how you track patients after discharge today — what tools, who's responsible, and how timely is the data?", "Understand manual vs. automated ADT; identify spreadsheet/portal workarounds", "Agentic AI Discovery Jun26; Readmission Discovery Jun25"],
  ["Pop Health", "Workflow", "Care Coordinator / Admin", "How do you get notified when a patient is discharged or transitions between settings? How reliable is that signal?", "Probe ADT feed quality, delays, missing pings", "Agentic AI Discovery Jun26"],
  ["Pop Health", "Workflow", "Care Coordinator / Admin", "What does your 30-day follow-up process look like? Where do patients fall through the cracks?", "Surface missed TCM windows, 48h / 14-day touchpoints", "Agentic AI Discovery Jun26; Quality Clinics Discovery"],
  ["Pop Health", "Data / Integration", "Admin / Manager", "Which ADT or HIE feeds are currently in play? What are the main data quality issues you face?", "Qualify integration complexity; expose deduplication pain", "Agentic AI Discovery Jun26"],
  ["Pop Health", "Data / Integration", "Admin / Manager", "What data do you use to identify high-risk / high-readmission patients — claims, ADT, EHR, SDOH?", "Understand data availability and gaps for risk models", "Agentic AI Discovery Jun26; Readmission Discovery Jun25"],
  ["Pop Health", "Workflow", "Care Coordinator", "What are you currently tracking? (ADT coverage, PCP seen in 7 days post-discharge, unplanned readmission rate, ED visits)", "Baseline metrics the client already monitors; WTP signal", "Readmission Discovery Jun25"],
  ["Pop Health", "Pricing / WTP", "Manager / Admin", "What's your biggest pain — data flow, actionability, or cost visibility? Can you translate each readmission into dollars?", "Qualify WTP; probe cost-of-status-quo", "Readmission Discovery Jun25"],
  ["Pop Health", "Pricing / WTP", "Manager / Admin", "Do you think a solution like this would be worth ~20 cents PMPM? What would make it worth more?", "Direct WTP probe used in June 2025 validation calls", "Readmission Discovery Jun25"],
  ["Pop Health", "Agentic", "Care Coordinator / Manager", "If you could hand off one part of post-discharge workflow entirely to an AI agent, what would it be and why?", "Identify highest-pain autonomous task; frame design-partner fit", "Agentic AI Discovery Jun26"],
  ["Pop Health", "Trust", "Care Coordinator / Clinician", "What would have to be true for your team to trust an agent's output — for clinical tasks vs. administrative tasks?", "Trust threshold for autonomy; key for agentic product positioning", "Agentic AI Discovery Jun26"],
  ["Quality", "Workflow", "Care Team / Quality Coordinator", "Walk me through your quality / care gap workflow today — who owns each step, what tools do you use, and how often?", "Understand visit-based vs. gap-based trigger; identify manual steps", "Quality Clinics Discovery; HIE/Quality/Claims Notion"],
  ["Quality", "Data / Integration", "Care Team / Admin", "Where do you get your care gap data — payer portals, HIE, EMR? How do you reconcile when sources conflict?", "Surface data trust issues; payer portal dependency", "Quality Clinics Discovery; HIE/Quality/Claims Notion"],
  ["Quality", "Workflow", "Care Team / Quality Coordinator", "How do you close a gap today? What's the most time-consuming step, and where does work slip?", "Map closure workflow; find slippage in CPT coding, documentation", "Quality Clinics Discovery"],
  ["Quality", "Trust", "Clinician / Provider", "Do you trust Navina's gap data as much as your payer portal? What would need to change for it to become your source of truth?", "Trust blocker for daily workspace adoption — critical for go-live readiness", "June 2026 Onsite Plan"],
  ["Quality", "Data / Integration", "Admin / Manager", "How do you handle exclusions? Which payer specs do you follow, and how do you track them across contracts?", "Exclusion logic is a major differentiator; understand per-payer complexity", "Quality Clinics Discovery (MPG detail)"],
  ["Quality", "Workflow", "Provider / Clinician", "What does a provider's in-visit or post-visit gap closure experience look like today? Where does it break down?", "Validate in-visit entry point; scoreboard concept interest", "June 2026 Onsite Plan; Quality Clinics Discovery"],
  ["Quality", "Pricing / WTP", "Manager / Admin", "What would make a quality tool a must-have vs. a nice-to-have for your organization?", "Probe value anchoring and switching cost", "Analytics Discovery Deck"],
  ["Analytics", "Goals", "VBC Leader", "What does success in your value-based contracts look like this year — which measures or outcomes are you on the hook for?", "Anchor on contract-level accountability before showing the product", "Analytics Platform Discovery Deck"],
  ["Analytics", "Goals", "VBC Leader", "Where could analytics most move the needle: risk capture, quality/Stars, cost & utilization, or network leakage?", "Prioritize which analytics views matter most", "Analytics Platform Discovery Deck"],
  ["Analytics", "Workflow", "Clinic Manager", "What do you need to see to run your day — patient lists, open gaps, scheduled visits, provider workload?", "Operational vs. strategic needs; daily vs. monthly cadence", "Analytics Platform Discovery Deck"],
  ["Analytics", "Data / Integration", "VBC Leader / Manager", "What tools are you using today for analytics — PowerBI, Excel, payer portals, other? Where do they fall short?", "Map current stack; identify unified payer+EMR view as differentiator", "June 2026 Onsite Plan"],
  ["Analytics", "Data / Integration", "VBC Leader", "What reports do you build manually today that you wish were automated?", "Identify highest-friction reporting tasks", "Analytics Platform Discovery Deck"],
  ["Analytics", "Trust", "VBC Leader / Manager", "What does trust in the numbers require — data freshness, source transparency, reconciliation with your own reports?", "Data trust is a recurring blocker; need specifics per client", "Analytics Platform Discovery Deck; June 2026 Onsite Plan"],
  ["Analytics", "Workflow", "Manager / Admin", "How does insight travel from a VBC leader down to the clinic and individual provider today?", "Understand decision-to-action flow; identify where analytics stalls", "Analytics Platform Discovery Deck"],
  ["Analytics", "Pricing / WTP", "VBC Leader / Manager", "How would you measure the platform's value in 90 days and at end of the contract year?", "Establish success metrics upfront; anchor ROI conversation", "Analytics Platform Discovery Deck"],
  ["Agentic", "Agentic", "Care Team / Manager", "When you say 'agentic AI', what does the ideal end state look like — what does the agent do without a human in the loop?", "Understand autonomy expectations; calibrate scope of agentic MVP", "Agentic AI Discovery Jun26"],
  ["Agentic", "Workflow", "Care Coordinator / RN / MA", "Who does chart prep today, and how long does it take per patient? What does 'ready' look like?", "Baseline TCM/chart prep effort for ROI framing", "Agentic AI Discovery Jun26"],
  ["Agentic", "Trust", "Clinician / Manager", "Where would you want an agent to act autonomously vs. surface a recommendation for human review?", "Define autonomy boundary — clinical vs. admin split", "Agentic AI Discovery Jun26"],
  ["Agentic", "Data / Integration", "Admin / IT", "Which TCM elements are hardest to execute consistently — interactive contact, med reconciliation, face-to-face visit, or billing?", "Prioritize which TCM step benefits most from automation", "Agentic AI Discovery Jun26"],
  ["Agentic", "Pricing / WTP", "Manager / Admin", "How would you measure success in 90 days? TCM billing capture, readmission rate, time saved, coordinator capacity?", "Frame success metrics for commercial conversation", "Agentic AI Discovery Jun26"],
  ["General", "Workflow", "All Personas", "Who are the actual users of this workflow — roles, data fluency, and how much time they spend on it today?", "Persona qualification; understand who we need to win over", "Analytics Discovery Deck; Agentic AI Discovery Jun26"],
  ["General", "Data / Integration", "Admin / IT", "Who owns data access and security decisions on your side?", "Identify decision-maker for integration approvals", "Agentic AI Discovery Jun26"],
  ["General", "Goals", "Manager / VBC Leader", "What have you already tried (tools, staffing, process changes) and where did it fall short?", "Competitive intel; understand prior failed solutions", "Agentic AI Discovery Jun26; BioSTL Meeting Questions"],
  ["General", "Pricing / WTP", "Manager / Admin", "What would make this a must-have vs. a nice-to-have for your organization?", "Value anchoring question — use in every discovery session", "Analytics Discovery Deck"],
  ["Quality", "Trust", "Quality Coordinator / Provider", "Do you trust Navina's gap data as much as your payer portal right now? What would need to change for it to become your source of truth?", "Trust is the #1 adoption blocker — probe the specific gap (payer lag, status sync, evidence accuracy)", "Jan/Sep 2025 onsites; CareMore Jun 26"],
  ["Quality", "Workflow", "Quality Coordinator", "When you work the gaps, do you go patient-by-patient or measure-by-measure? How do you prioritize?", "Understand visit-first vs. gap-first trigger; filter/sort needs", "Quality Clinics Discovery; Sep 25 onsite"],
  ["Quality", "Workflow", "Quality Coordinator", "How do you close a gap today — what are the exact steps from identifying it to getting payer credit?", "Map closure workflow end-to-end; find manual steps, fax/portal steps, lag points", "Quality Clinics Discovery; DHG Jan 25"],
  ["Quality", "Data / Integration", "Quality Coordinator / Manager", "What happens when your CGF only contains open measures — how do you know when a gap you worked is actually closed?", "Probe payer lag and status sync pain; Valora and SFP both hit this", "Notion: Quality Onsite Jan 25 / Sep 25"],
  ["Quality", "Workflow", "Provider / MA", "What is your in-visit or post-visit workflow for coding quality measures — who does what, and when?", "Providers work gaps during/after visit, not just care team; CPT push vs. manual coding", "CareMore Jun 26; DHG Jan 25; NOMS Jan 25"],
  ["Quality", "Pain Points", "Quality Coordinator", "Which quality measures are the hardest to close consistently, and why?", "Surface measure-specific pain: colorectal (10yr docs), adherence (pharmacy gap), statin (GoodRx cash)", "Quality Clinics Discovery; Southeast Jan 25"],
  ["Quality", "Workflow", "Manager", "How do you track performance over time — do you have a scorecard, and does it go to the provider level?", "Validate scoreboard concept; NOMS provider scoreboard drove highest engagement", "Quality Onsite Jan 25; CareMore Jun 26"],
  ["Analytics", "Workflow", "VBC Leader / Manager", "Walk me through how a data insight travels from you to the clinic and to the individual provider. Where does it stall?", "Find the breakdown in decision-to-action flow; attribution gap is common", "Analytics Discovery Deck; June 2026 onsite"],
  ["Analytics", "Data / Integration", "VBC Leader", "Do you have payer contract data unified with your EMR data in one view today? What tool do you use?", "Validate unified payer+EMR view as primary differentiator; everyone uses PowerBI/Excel to fill this gap", "June 2026 Onsite Plan; NOMS DS team Jan 25"],
  ["Analytics", "Trust", "VBC Leader / Manager", "How often does your analytics data contradict what your payer portal shows? How do you reconcile?", "Trust in numbers requires freshness + reconciliation — probe reporting lag tolerance", "Analytics Discovery Deck; Loudoun; DHG"],
  ["Analytics", "Workflow", "Manager / Admin", "How do you manage attribution — patients you're being scored on but not actually seeing?", "Attribution management is a recurring critical pain across NOMS, DHG, Arches", "NOMS DS team Jan 25; Arches Jun 26; Loudoun"],
  ["Risk / Dx", "Workflow", "Provider", "Walk me through how you review a patient's diagnoses in Navina — what do you look at first, and what do you typically skip?", "Understand attention flow; most providers go straight to unaddressed HCC, skip addressed section", "Dx Onsite Sep 24; Sep 25"],
  ["Risk / Dx", "Trust", "Provider", "When Navina suggests a diagnosis, what makes you trust it enough to accept it without opening the underlying document?", "Trust threshold varies by provider; evidence table is verification safety net for most", "Dx Onsite Sep 25 — Aegis, SFP, CVFP"],
  ["Risk / Dx", "Workflow", "Provider", "How do you document a diagnosis after accepting it in Navina — what's your A&P process?", "Documentation workflow varies widely; auto-doc is universally desired but flow differs per provider", "Dx Onsite Sep 25; Sep 24"],
  ["Risk / Dx", "Pain Points", "Provider", "What are the most common false or irrelevant suggestions you see in Navina? What do you wish it would stop showing?", "Noise reduction: CKD fluctuations, obesity sub-codes, hyperlipidemia as companion with no HCC value", "Arches Jun 26; Dx Onsite Sep 24"],
  ["Ambient", "Workflow", "Provider", "Walk me through how you use an ambient documentation tool today — when do you start/stop recording, and how do you finalize the note?", "Understand current workflow end-to-end; phone vs. laptop, editing in tool vs. EMR, consent", "User feedback on other Ambient tools; V0 onsite Aug 25"],
  ["Ambient", "Pain Points", "Provider", "What does your current ambient tool do well, and what's the biggest thing that frustrates you about it?", "Competitive positioning: probe Freed strengths (mobile, templates), Suki weaknesses (A/P push, confabulation)", "User feedback on other Ambient tools; DTC/HHHN/NOMS interviews"],
  ["Ambient", "Trust", "Provider", "How often do you find errors in AI-generated notes? What kinds of errors concern you most?", "Hallucination fear is universal; accuracy of dates, diagnoses, small-talk exclusion are key trust factors", "V0 Go Live Onsite Aug 25; DTC/HHHN feedback"],
  ["Ambient", "Workflow", "Provider", "What would the ideal note look like after a visit — what sections, what level of detail, in what format?", "Note style preferences vary: concise vs. narrative, per-Dx vs. per-encounter, bullets vs. prose", "Dx Onsite Sep 25; V0 Go Live Onsite Aug 25"],
  ["Pop Health", "Workflow", "Care Manager / Admin", "How do you identify and prioritize patients for care management outreach today? What tools do you use?", "Manual ADT everywhere — Excel, payer portals, daily files; care management impact tracking is unmet need", "June 2026 Onsite Plan; NOMS Jan 25"],
  ["Pop Health", "Trust", "Care Manager", "How would you know if your care management interventions are actually making a difference? Can you show that today?", "'How do I show a managed patient is doing better than a non-managed one?' — universal unmet need", "NOMS Jan 25; June 2026 Onsite Plan"],
  ["Agentic", "Workflow", "Care Coordinator / Manager", "If an AI agent handled your most time-consuming task end-to-end with no human in the loop, what would that task be?", "Identify the highest-pain fully automatable step; sets scope for agentic MVP", "Agentic AI Discovery Jun26"],
  ["Agentic", "Trust", "Manager / Admin", "What would have to be true — in terms of accuracy, audit trail, or controls — for your team to trust an agentic workflow for clinical tasks?", "Trust threshold for full autonomy; CareMore: 'AI should not push final docs without human approval'", "Agentic AI Discovery Jun26; CareMore Jun 26"],
  ["Agentic", "Workflow", "Care Coordinator / RN", "Walk me through your TCM process today, from discharge notification to the final follow-up. Who owns each step?", "Map the full TCM ownership chain; identify handoff gaps and manual steps", "Agentic AI Discovery Jun26"],
  ["Agentic", "Workflow", "Care Coordinator", "Where does work fall through the cracks — missed TCM windows, incomplete charts, patients who slip past the 48-hour or 14-day touchpoints?", "Surface highest-value automation targets; quantify revenue leakage", "Agentic AI Discovery Jun26"],
  ["Agentic", "Workflow", "Care Coordinator / Billing", "How do you track the TCM clock and ensure compliance for billing? Where do you lose revenue today?", "Quantify TCM billing leakage; validate agentic billing capture use case", "Agentic AI Discovery Jun26"],
  ["Agentic", "Pain Points", "Manager / Admin", "What triggered the interest in an agentic solution now? What is the cost of the status quo?", "Understand urgency and quantify pain; essential for ROI framing", "Agentic AI Discovery Jun26"],
  ["Agentic", "Workflow", "Care Coordinator / RN / MA", "What goes into a prepped chart for a post-discharge visit? What sources do you pull from?", "Define chart prep scope — ADT, labs, notes, meds; input for agentic chart prep spec", "Agentic AI Discovery Jun26"],
  ["Agentic", "Workflow", "Care Coordinator / RN", "How much of chart prep is summarization vs. judgment — flagging what matters clinically?", "Distinguish automatable (summarization) from human-in-loop (clinical judgment) tasks", "Agentic AI Discovery Jun26"],
  ["Pop Health", "Workflow", "Care Manager / Manager", "How do you identify high-risk / high-readmission patients today — model, rules, or gut feel?", "Baseline risk stratification maturity; qualify need for predictive model vs. rules engine", "Agentic AI Discovery Jun26; Readmission Discovery Jun25"],
  ["Pop Health", "Workflow", "Care Manager", "What would change in your workflow if you had a reliable readmission risk signal at the point of transition?", "Validate workflow impact of risk stratification; probe what 'reliable' means to them", "Agentic AI Discovery Jun26"],
  ["Agentic", "Trust", "Clinician / Manager", "What level of autonomy are you comfortable with for clinical vs. administrative tasks?", "Map the autonomy spectrum — auto-execute vs. suggest-and-approve per task type", "Agentic AI Discovery Jun26"],
  ["Analytics", "Workflow", "VBC Leader / Manager", "When you first open the analytics overview, what are you seeing — what stands out and what do you think it's intended to help you do?", "Baseline comprehension test; validate whether page hierarchy and KPI grouping matches mental model", "Notion: POP user feedback"],
  ["Analytics", "Goals", "VBC Leader", "Does the overview page feel more strategic, operational, or analytical to you — and what would make it feel more actionable?", "Classify how leaders consume the page; drives whether to lead with KPIs vs. action prompts", "Notion: POP user feedback"],
  ["Analytics", "Goals", "VBC Leader / Manager", "When you see a RAF score, what else do you need to know to make it useful — how much comes from recapture, suspects, and what opportunity is still open?", "Carlos (Aegis): RAF alone is insufficient — context of recapture vs. suspect vs. open opportunity is what drives decisions", "Notion: POP user feedback"],
  ["Analytics", "Goals", "VBC Leader", "Do you use recapture rate as a primary KPI? How does it connect to your financial projections?", "Carlos uses HCC × $ value × 12 months = PMPM impact; recapture rate is the operational lever that drives it", "Notion: POP user feedback"],
  ["Analytics", "Trust", "VBC Leader / Actuary", "When we show 'potential RAF based on all patients,' does that feel like a realistic target to you — or is it misleading?", "Carlos flagged this as creating unrealistic expectations; not all patients will have visits, not all suspects confirmed", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "VBC Leader / Manager", "How do you prioritize your top opportunities — by financial impact, clinical impact, or estimated effort?", "Joe: prioritizes by financial impact first, then clinical; Carlos wants RAF/financial impact per opportunity shown", "Notion: POP user feedback"],
  ["Analytics", "Goals", "Manager / Clinic Manager", "Do you set quarterly or annual targets for HCC gap closure — and would a target line on the trend chart help you track progress?", "Carlos uses Q1:50%, Q2:75%, Q3:90%, Q4:93% targets; a target line on the HCC gap chart was directly requested", "Notion: POP user feedback"],
  ["Analytics", "Data / Integration", "VBC Leader", "Is membership growth or decline visible in your current analytics — and how important is year-over-year trend vs. point-in-time numbers?", "Carlos and Joe both flagged missing membership trend; Joe also wants annual churn rate and MA vs. ACO segmentation", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "VBC Leader / Manager", "Who are the different roles that consume analytics in your organization — and do they need different views or different levels of detail?", "Joe: C-level needs high-level KPIs; regional leaders need region view; clinic managers need provider level; outreach teams need workspace only", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "Manager / Admin", "Do regional managers need to see their own performance separately — and what's the most important filter for their view?", "Joe: regional filter is very important; regional managers need their own performance view tied to provider and market", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "Care Manager / Manager", "When you look at a high-priority patient, what do you need to see at the patient level — current RAF, potential RAF, last visit, next visit, and previous year RAF?", "Scot (Revere): these five data points are needed to prioritize which patients to contact first", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "Care Manager", "For patients requiring HCC follow-up, do you need to distinguish scheduled vs. not-scheduled visits to know who to contact first?", "Scot: HCC follow-up tile needs scheduled vs. not-scheduled split — this determines outreach priority", "Notion: POP user feedback"],
  ["Analytics", "Goals", "Quality Leader / Manager", "Beyond the current star rating percentage, would it help to see how many patients are needed to reach the next star tier?", "Scot: wants 'X patients needed to move from 3→4 stars' shown alongside percentage; drives focused outreach", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "Care Manager / Admin", "When a care manager calls a patient from the platform, does that call note need to flow back into the EMR so clinic staff know why the patient was contacted?", "Scot (Revere): this is a hard requirement for their outreach workflow; without EMR sync, calls create information silos", "Notion: POP user feedback"],
  ["Analytics", "Workflow", "Care Manager / Admin", "How do you currently run outreach — campaigns (portal/email/SMS) for large groups vs. phone calls for specific patients? What would a combined workflow look like?", "Scot uses campaigns for bulk outreach and calls for specific patients; needs both to coexist in one tool", "Notion: POP user feedback"],
  ["Analytics", "Data / Integration", "VBC Leader / IT", "Your organization may already use tools like RoundingWell for outreach — would you need Navina to integrate with or replace those, or would an API be sufficient?", "Joe flagged that large orgs already have call center tools; API/integration path is the realistic adoption route", "Notion: POP user feedback"],
  ["Pop Health", "Goals", "VBC Leader / Manager", "What is your current Medical Loss Ratio, and what would a 1–2 point improvement mean in dollar terms for your organization?", "Anchor the financial ROI conversation; workshop data shows 1 MLR point = $4–16M/year for a 100K-member book", "Pop Health Advisors Workshop; Readmission Discovery Jun25"],
  ["Pop Health", "Workflow", "Care Manager", "When a patient is discharged, who gets the first notification and within how many hours — and what's the first action they're expected to take?", "Probe the 'last mile' of ADT-to-action; most orgs get the feed but the routing to the right person is broken", "Agentic AI Discovery Jun26; Readmission Discovery Jun25"],
  ["Pop Health", "Data / Integration", "Admin / IT", "Do you have a single view today that combines claims, ADT, EHR, and quality gap data in one place — or are you stitching these from separate tools?", "Validate the fragmentation problem; foundation for positioning Navina as unified data layer", "Pop Health Advisors Workshop"],
  ["Analytics", "Trust", "VBC Leader", "How often does your analytics refresh — and when there's a lag between your BI tool and the payer portal, which do you trust more and why?", "Probes data freshness tolerance and source-of-truth hierarchy; trust gap between Navina and payer portals is the #1 adoption blocker", "Analytics Platform Discovery Deck; Quality Onsite Sep 25"],
  ["Agentic", "Pricing / WTP", "Manager / Admin", "If an agent could fully automate your TCM billing capture and recover missed revenue, how much is that worth to you per month — and at what price point does it become a no-brainer?", "WTP probe tied to concrete revenue recovery; TCM billing leakage is typically $200–400 per missed encounter", "Agentic AI Discovery Jun26"],
  ["General", "Goals", "Manager / VBC Leader", "What does your 2026 VBC contract performance look like — are you in upside only, or do you have downside risk exposure?", "Qualify urgency; downside risk orgs have 10x the motivation to invest in pop health tooling", "Pop Health Advisors Workshop; Analytics Platform Discovery Deck"],
];

// [productArea, theme, persona, oneLiner, content, date, wtp, source, client]
const INSIGHTS: string[][] = [
  ["Quality", "Workflow", "Juan Rosa (Quality Lead)", "Not using Quality yet — building the process first, plan rollout in April with 2025 files", "Not using Quality yet — building the process first, plan rollout in April with 2025 files. Don't see value in push CPT actions; only need post-visit coding accuracy. Export not needed.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "DHG"],
  ["Quality", "Data / Integration", "Juan Rosa", "Faxing supplemental data to payers (Aetna has its own form)", "Faxing supplemental data to payers (Aetna has its own form). Need full progress notes for payer submission — snippet Navina provides is not enough. Want insurance member ID in workspace.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "DHG"],
  ["Quality", "Workflow", "Stephanie, Cassandra, Dr. Rodriguez", "CGF contains only open measures", "CGF contains only open measures — when next file arrives and measure missing, Navina still shows OPEN. Stephanie still uses own Excel file; main blocker is measures not showing compliant in next CGF. Going over ~200 visits/day.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Valora"],
  ["Quality", "Data / Integration", "Stephanie", "Exclusion updates done via email to payer", "Exclusion updates done via email to payer. Two bugs surfaced: Z code not closing cervical cancer measure; FOBT showing as Cologuard incorrectly.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Valora"],
  ["Quality", "Workflow", "Debbie", "No formal workflow for closing care gaps", "No formal workflow for closing care gaps; only occasional coders from rev cycle team use quality workspace. Want to prioritize patients with most open gaps by clinic. Want bird's-eye measure view — patient list per measure.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Southeast (SEMG)"],
  ["Quality", "Pain Points", "Debbie + Eric", "Statin measures hard to close — patients paying cash via GoodRx not tracked by insurance", "Statin measures hard to close — patients paying cash via GoodRx not tracked by insurance. No mechanism triggering providers or care team to discuss medication adherence. Hiring ~5 people dedicated to gap closure.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Southeast (SEMG)"],
  ["Quality", "Data / Integration", "Debbie", "Want to download reports from workspace and push documents to Veradigm", "Want to download reports from workspace and push documents to Veradigm — currently printing and scanning into chart. Want bulk submission output file for payers.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Southeast (SEMG)"],
  ["Quality", "Pain Points", "Angela, Quality Coordinators", "Not using Quality at all", "Not using Quality at all — 'insights aren't actionable.' To close a gap: must send a visit note, which doesn't save time because they're already in the chart. Traditional Medicare doesn't send care gap files.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Aylo"],
  ["Quality", "Workflow", "Angela, Mikeba, MaryAnn (Quality Coordinators)", "Requested: PDF with gap closure evidence + most recent signed office note together", "Requested: PDF with gap closure evidence + most recent signed office note together. Notification when measure goes from non-compliant to compliant. Reminder feature shown — team loved it.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Aylo"],
  ["Quality", "Workflow", "Jenn, Holley", "Built quality workflow in EPIC", "Built quality workflow in EPIC — dashboard shows all metrics per provider with drill-down to patient level. Use Navina centrally for quality — value is matching with payer gap files plus unstructured data.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "NOMS (Quality team)"],
  ["Quality", "Data / Integration", "Jenn", "EPIC automatically adds CPT codes after documented procedures — no need for push CPT", "EPIC automatically adds CPT codes after documented procedures — no need for push CPT. Monthly batch supplemental data sent to each payer. Issue: inactive patients hard to remove from CGF.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "NOMS (Quality team)"],
  ["Quality", "Workflow", "Marilyn, Joe, Pam", "Small ACO focused on developmentally disabled population", "Small ACO focused on developmentally disabled population. No centralized quality teams; heavy reliance on providers. AWV is primary focus. Only 400 of 5,300 members can get support from call center. Risk score is most important metric.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "AICNY"],
  ["Quality", "Workflow", "Quality Team", "Manages everything in Google Sheets", "Manages everything in Google Sheets. Pulls daily Athena reports for tomorrow's patients, cross-references payer gap files. Two workflows: (1) visit-driven; (2) measure-driven. Submits directly to payer portals same day.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "SFP"],
  ["Quality", "Trust", "Quality Team", "See Navina as 'an extra step' compared to Excel", "See Navina as 'an extra step' compared to Excel. Have never received false gaps from payer — every gap is considered real. Navina still shows gaps as open after closed via payer portal. Evidence/eligibility logic sometimes unclear.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "SFP"],
  ["Quality", "Pain Points", "Quality Team", "Only want HEDIS measures — Navina shows all including MRA, creating noise", "Only want HEDIS measures — Navina shows all including MRA, creating noise. Want quick filterable/exportable patient lists by measure. Medication adherence gap: med use closes gap via payer but Navina keeps it open.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "SFP"],
  ["Quality", "Workflow", "Quality Manager", "Workflow starts with pulling tomorrow's schedule", "Workflow starts with pulling tomorrow's schedule. Close gaps in-visit. Call unscheduled patients with gaps, offer transportation. Source of truth = payer portals in real-time; monthly spreadsheets lag ~30 days.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "Primary Med"],
  ["Quality", "Trust", "Quality Manager", "No care gap files had been uploaded before the visit", "No care gap files had been uploaded before the visit. Low adoption — providers don't have Navina ECW overlay installed. 'Too much data' — prefer simple focused tables like Excel.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "Primary Med"],
  ["Quality", "Workflow", "Janae (Quality Manager)", "Still managing via Microsoft Teams + Excel (color-coded manually: yellow=pending, green=closed)", "Still managing via Microsoft Teams + Excel. Navina seen as 'upscale spreadsheet,' not central to process. Providers ARE using Navina daily during encounters. Managers gamify usage with competition between providers.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "DHG (Sep)"],
  ["Quality", "Pain Points", "Janae", "Requests: referrals workflow (current ECW telephone encounter is cumbersome)", "Requests: referrals workflow (want auto-fax to diagnostic centers). Want projections in dashboard — 'close 23 gaps/week to finish by X date.' Occasional missing/incorrect evidence, especially hospital records.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "DHG (Sep)"],
  ["Quality", "Workflow", "Quality Team", "Extremely high engagement (100%) and address rate (97%)", "Extremely high engagement (100%) and address rate (97%). Two providers on iPads — Navina doesn't support iPad. Request: BP alert popup if above 139/X at point of care. Very interested in HIE and auto-doc feature.", "Aug 2025", "", "Notion: Quality Onsite Sep 25", "SFP (Aug 2025 pre-visit)"],
  ["Quality", "Trust", "Stephanie Clements (VP Risk & Quality), Laura Stankovic", "Trust is core driver of adoption — users will not use a tool they don't trust", "Trust is core driver of adoption — users will not use a tool they don't trust. Discrepancies between Navina and HEDIS engine (CareMore's source of truth, refreshes weekly) erode confidence. Stability, accuracy, and clear data sourcing are prerequisites for go-live.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Quality", "Workflow", "Quality Leadership + MAs", "Status confusion is #1 friction: users confused why a clinically compliant measure still requires action", "Status confusion is #1 friction. Pending submission bucket at POC is 'actively misleading.' Requested: remove pending submission from POC, create single consolidated status with clear action guidance.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Quality", "Workflow", "Mayra (MA)", "MA exam prep is entirely manual and paper-based", "MA exam prep is entirely manual and paper-based — fills template by hand, prints, physically walks to provider. Takes ~1 hour for 20 patients. Open gaps section maps directly to what Navina surfaces — clear substitution opportunity.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Quality", "Data / Integration", "Abi, Chauntey", "Multiple open data issues: HbA1c >9% mapping wrong, Verda/Clever Care showing as payers incorrectly", "Multiple open data issues: HbA1c >9% mapping wrong, Verda/Clever Care showing as payers incorrectly, SUPD mapped to SPD, event-based measures merging two events into one, CBP measure overwritten by Navina incorrectly.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Quality", "Workflow", "Laura Stankovic", "Exclusions are a high-value workflow — Laura uses them to build chase lists", "Exclusions are a high-value workflow — Laura uses them to build chase lists. Stars team works with contracted community providers and builds chase lists manually. Pending submission bucket removal from POC was a direct, specific request.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Quality", "Workflow", "Dr. Gellis (CEO), Sam Sager", "HCC/Risk feedback session with providers (Megan, Valley Medical Group)", "HCC/Risk feedback session with providers (Megan, Valley Medical Group). Covered three tracks: risk/HCC feedback, analytics discovery, roadmap alignment.", "Jun 2026", "", "Notion: Arches Onsite Jun 26", "Arches"],
  ["Quality", "Data / Integration", "Dr. Bassi", "Open items: Missing A1C data on Quality Analytics tab (ticket NA-25301)", "Open items: Missing A1C data on Quality Analytics tab (ticket NA-25301). A1C measure logic confusing — 'Poor Control' specification unclear to providers. Request for 'Contact Us' button tied to specific patient in Quality Workspace.", "Jun 2026", "", "Drive: Pop Onsite Kit Jun 26", "Summit NJ (VillageMD)"],
  ["Quality", "Workflow", "Rebecca (Becy) — Care Team", "Work only with EMR data — can't normalize/reconcile payer care gap reports", "Work only with EMR data — can't normalize/reconcile payer care gap reports. Process not triggered by payer gap files. Status visibility critical: Open gap / Payor gap / Data sent to payor.", "Jan 2023", "", "Quality Clinics Discovery", "NOMS (2023)"],
  ["Quality", "Data / Integration", "Rebecca (Becy)", "Gaps show as open even after supplemental data feeds sent", "Gaps show as open even after supplemental data feeds sent — 30/60/90 day processing lag on payer side. Ophthalmology data not on HIE; HbA1c from small endocrinology offices not sending labs.", "Jan 2023", "", "Quality Clinics Discovery", "NOMS (2023)"],
  ["Quality", "Workflow", "Sandra Ramnarine, Carol White, Mariaelena", "Workflow split: 'clinical' (actual open gaps) vs. 'clerical' (already documented)", "Workflow split: 'clinical' (actual open gaps) vs. 'clerical' (already documented). Need filter by status. Want to work ahead of appointment date. Snooze functionality needed.", "2023", "", "Quality Clinics Discovery", "MPG"],
  ["Quality", "Data / Integration", "Carol White", "Adherence data from EHR only shows prescriptions — need 'filled' data from prescription claims", "Adherence data from EHR only shows prescriptions — need 'filled' data from prescription claims. Part D claims needed to close adherence metrics. Want unified system consolidating all sources.", "2023", "", "Quality Clinics Discovery", "MPG"],
  ["Quality", "Pain Points", "Quality Team", "Colorectal most time-intensive — requires combing 10 years of documents", "Colorectal most time-intensive — requires combing 10 years of documents. VA pharmacy and cash prescriptions (GoodRx) create zero-visibility adherence gaps. Triple-weighted adherence measures (statins, hypertension, diabetes) are highest priority.", "2023", "", "Quality Clinics Discovery", "MPG"],
  ["Quality", "Pain Points", "Lynn", "No dedicated quality team — pre-visit MAs do quality flow via Athena care gap feature", "No dedicated quality team — pre-visit MAs do quality flow via Athena care gap feature. Carrier scorecards are 'nearly worthless' due to data delay. Difficult to track/close gaps for patients with no upcoming appointments.", "May 2022", "", "Quality Clinics Discovery", "DTC"],
  ["Quality", "Data / Integration", "Dr. Cibotti", "Multiple EMRs makes gap verification very labor-intensive", "Multiple EMRs makes gap verification very labor-intensive. Provider communication via Sticky Notes in EMR — often ignored. Using Arcadia for claims review. Three main contracts: Harvard, Tufts, BCBS.", "Jun 2022", "", "Quality Clinics Discovery", "BILH"],
  ["Quality", "Workflow", "Bethsaida Eliazar (HEDIS team, 4 people)", "16 contracts", "16 contracts. Receive reports from insurance → review patient audit → communicate with provider re: missing meds/screening. Medication adherence checked every 2 weeks (time-sensitive).", "Jan 2023", "", "Quality Clinics Discovery", "MCF"],
  ["Quality", "Pilot Feedback", "Sandra (Quality Lead), Joe Hefner", "Opted out of Quality Workspace pilot", "Opted out of Quality Workspace pilot. Reasons: panel too small (~2,000 MA members); 3-week pilot too short; quality program brand new. Quality Workspace at 50¢ PMPM = >60% of total Navina cost. Dashboard experience was seamless; AI found genuinely helpful external docs for gap closure.", "May 2026", "", "Notion: Navina Quality Value & Pilot Feedback Session", "Upperline Health"],
  ["Quality", "Product Feedback", "Sandra", "BP and KED measures showed external docs on dashboard but cannot be closed from external docs", "BP and KED measures showed external docs but cannot be closed from them — causes staff confusion. Wants: last appointment date, next appointment date, next rendering provider in dashboard.", "May 2026", "", "Notion: Navina Quality Value & Pilot Feedback Session", "Upperline Health"],
  ["Quality", "Feedback", "Stewart, Kim, Phuong", "Ambient co-pilot strong adoption and satisfaction", "Ambient co-pilot strong adoption and satisfaction. Quality session Dec 2025: kicked off quality program discussion — interested in workspace. Patient-based analytics beta client.", "2025-2026", "", "Slack: customer-harmonycares; Notion: various", "Harmony Cares"],
  ["Quality", "Workflow", "Stewart, Kim", "Quality session (Dec 31 2025): kicked off quality program discussion — interested in workspace", "Quality session (Dec 31 2025): kicked off quality program discussion. Ambient auto-documentation demo (Dec 8 2025): strong interest. Jul 26 Noa comment: 'without tagging I'm afraid a lot of these updates will get lost' — flagging update visibility issue.", "Dec 2025", "", "Slack: customer-harmonycares", "HarmonyCares"],
  ["Pop Health", "Workflow", "Juan Rosa", "ADT files from Humana sent to inbox manually — care member reviews sheet by sheet", "ADT files from Humana sent to inbox manually. ADT data from ENS daily files via hospitals. Uses internal PowerBI data warehouse for admissions; wants case management tool.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "DHG"],
  ["Pop Health", "Workflow", "Dr. Rodriguez team", "Happy with current pop health tool (Anil)", "Happy with current pop health tool (Anil). But impressed by ADT admissions demo — solves a real pain. ADT done manually today via payer portal file (Devoted generates daily reports).", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Valora"],
  ["Pop Health", "Workflow", "Debbie", "Manual ADT process — transition care team for some hospitals, sporadic", "Manual ADT process — transition care team for some hospitals, sporadic. Interested in SDOH analytics — just starting, community health workers certified, no full workflow yet.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "Southeast (SEMG)"],
  ["Pop Health", "Workflow", "Jenn", "Want to show that care management interventions lead to better outcomes vs. non-managed patients", "Want to show that care management interventions lead to better outcomes vs. non-managed patients — 'how do I show that a patient in care management is resulting better?' Currently using Compass Rose (EPIC module) for care management.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "NOMS (Quality team)"],
  ["Pop Health", "Workflow", "Quality Team", "ADT/readmissions tracked manually in Excel", "ADT/readmissions tracked manually in Excel. Frustrated by duplicate/messy HIE data. Need deduplication.", "Sep 2025", "", "Notion: Quality Onsite Sep 25", "SFP"],
  ["Pop Health", "Workflow", "Quality Team", "Admissions/readmission interesting but everything done manually today", "Admissions/readmission interesting but everything done manually today. Want any tool to reduce manual work.", "Aug 2025", "", "Notion: Quality Onsite Sep 25", "SFP (Aug 2025 pre-visit)"],
  ["Analytics", "Data / Integration", "Juan Rosa", "All claims ingested to their data warehouse via PowerBI", "All claims ingested to their data warehouse via PowerBI. Want discrepancy report between provider in CGF and EMR. Attribution mismatch is known issue.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "DHG"],
  ["Analytics", "Data / Integration", "Brian, Zach, Antony (Head of DS)", "Payer + data integration is huge", "Payer + data integration is huge — need to follow patient attribution (being scored for patients they are not seeing). 98% automated match rate; 2% manual. Devoted is only fully automated payer; others by email/download.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "NOMS (DS team)"],
  ["Analytics", "Workflow", "DS Team", "Weekly full run + nightly incremental + manual update", "Weekly full run + nightly incremental + manual update. Running on ~200K active population. Reports include: MRN, name, DOB, age, next PCP visit, outcome, is external, PCP, care manager, last A1c value.", "Jan 2025", "", "Notion: Quality Onsite Jan 25", "NOMS (DS team)"],
  ["Analytics", "Workflow", "Stephanie Clements", "Currently runs analytics at pod level, not provider level", "Currently runs analytics at pod level, not provider level. Known mismatch: providers are measured on attributed patients but incentivized on assigned patients. Using Navina API for data only. Home-grown HEDIS engine is their source of truth.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Analytics", "Workflow", "Analytics Team", "Analytics session described as 'one of the more productive conversations on this topic.'", "Analytics session described as 'one of the more productive conversations on this topic.' Client to send follow-up questions. Navina Analytics opened as part of community-facing offering. Discussion on patient-based vs. visit-based metrics.", "Aug 2026", "", "Notion: Summit Medical Group x Navina Analytics Session", "Summit Medical Group"],
  ["Analytics", "Data / Integration", "Sam (Quality Lead), Dr. Gellis", "Downloading data and building API connection to replicate scores into Snowflake Cortex dashboards", "Downloading data and building API connection to replicate scores into Snowflake Cortex dashboards. Key issue: analytics reset at year start — need year-over-year trend visibility. RAP score definition mismatch: Navina uses 3-year cohort; Arches wants 1-year monthly cumulative.", "Jun 2026", "", "Notion: Arches Medical Onsite Jun 26", "Arches Medical"],
  ["Analytics", "Patient-Based", "Analytics team", "Patient-based analytics beta client", "Patient-based analytics beta client. Portrait Analytics Review session (Aug 12 2026): deep dive into patient portraits and analytics. Real value seen at MPG Texas and MPG FL. Request for direct escalation channel between support/field and development.", "Aug 2026", "", "Slack: customer-millennium-physician-group; Notion: Patient based solution feedback review", "Millennium Physician Group"],
  ["Analytics", "Workflow", "Wendy, Rachel (Risk), Kimberly, Antoine, Dana", "Weekly sync (Jan 9 2026): risk attribution and roster questions", "Weekly sync (Jan 9 2026): risk attribution and roster questions. Bi-weekly sync (Apr 1 2026): upcoming April onsite discussed. Analytics session (Aug 8 2026): one of the more productive conversations on analytics.", "Jan 2026", "", "Slack: customer-summit-medical-group", "Summit Medical Group"],
  ["Analytics", "Patient-Based", "Scott (POC)", "Discussion on moving from visit-based to patient-based analytics across entire platform", "Discussion on moving from visit-based to patient-based analytics across entire platform. Quality updates happen daily when files uploaded. Beta candidate for patient-based analytics validation.", "Mar 2026", "", "Notion: Revere - Product Discussion — New Analytics Platform", "Revere Medical Group"],
  ["Analytics", "Patient-Based", "Joe Hefner", "Navina transitioning from visit-based to patient-based analytics — key validation discussion", "Navina transitioning from visit-based to patient-based analytics — key validation discussion. Analytics feedback on V1 concept: positive engagement, interested in patient-based workflows.", "Feb 2026", "", "Notion: Joe Hefner | Upperline Health", "Upperline Health — Joe Hefner"],
  ["Analytics", "Workflow", "Analytics team", "Analytics working session: focus on patient-level view with attributed provider", "Analytics working session: focus on patient-level view with attributed provider. Actions on Patients concept discussed — proactive, action-oriented experience highlighting most impactful patient-based opportunities.", "Jul 2026", "", "Notion: Navina Analytics Working Session (Greater Good Health)", "Greater Good Health"],
  ["Analytics", "General", "Multiple clients (Slack channel)", "Mar 2026: over 2 weeks held 3 client validation sessions — quick feedback loops", "Mar 2026: over 2 weeks held 3 client validation sessions. Jan 2026 channel launch: aligned on project goal, reviewed V1 scope and out-of-scope items. Feedback: before opening to Florida groups, product cannot be in beta.", "Jan 2026", "", "Slack: analytics-patient-based-feedback-channel", "analytics-patient-based-feedback-channel"],
  ["Risk / Dx", "UI / Labels", "Dr. Geras, Dr. Walsh, PA Danielle, Dr. Ruggles, Dr. Hartman, Dr. Cutler, Dr. Kaftan, Dr. Hohman", "Dx Labels (Recapture/Suspect): Most providers hadn't noticed the labels or didn't know their meaning", "Term 'Recapture' unclear. After explanation, ~half found them helpful. Consensus: rename to 'Confidence Level: High/Medium' or 'Recommendation Strength'. Suspect subtypes are irrelevant to most.", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS providers (multiple)"],
  ["Risk / Dx", "UI / Sections", "Multiple providers", "Dx Sections (Addressed/Unaddressed HCC): Almost no one understood section names", "~50% see 'Addressed HCC' as noise; other 50% see clinical value. Request: sections by status (Open/Accepted/Rejected) preferred. Providers loved 'number of Dx to review' badge and 'clear the table' concept.", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS + Privia providers"],
  ["Risk / Dx", "Companion Codes", "Multiple providers", "Companion codes generally understood and seen as valuable", "Companion codes generally understood and seen as valuable. Consensus: if parent was already addressed in a previous encounter, don't show it again — only show the unaddressed one.", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS + Privia providers"],
  ["Risk / Dx", "Grouping", "Multiple providers", "Grouping by condition preferred by most vs. grouping by HCC", "Within group, sort by HCC value. Show all Dx expanded by default. Consensus: combining HCC group with condition subgroup would be ideal.", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS + Privia providers"],
  ["Risk / Dx", "Auto-Doc", "All providers", "Auto-documentation: ALL providers love this idea and can't wait for it", "Auto-documentation: ALL providers love this idea. Critical requirement: must be editable. Preferred per Dx (not per group or encounter). Dr. Walsh: 'Can we have this tomorrow please?'", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS + Privia providers"],
  ["Risk / Dx", "Clinical Summary Tab", "Multiple providers", "Most providers don't use or haven't seen the Clinical Summary tab", "Too long, too much information, should be a short paragraph. Best use case: new patients. 'It should be 4 sentences summary' (Privia).", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "NOMS + Privia providers"],
  ["Risk / Dx", "Other Pain Points", "Dr. Charleson & Group", "Want 'Hold All' and 'Reject All' buttons", "Want 'Hold All' and 'Reject All' buttons. CKD fluctuations trigger noise (new level each time). Fibrosis always incorrectly linked to pulmonary.", "Sep 2024", "", "Notion: Dx Onsite Visit Sep 24", "Privia providers"],
  ["Risk / Dx", "Grouping", "Dr. Elder Arroyo Nieto, Dr. Carlos, Dr. Hector Marti Hernandez", "Grouping well received overall", "Policy at Aegis: action on ALL diagnoses regardless of HCC value — 'Our policy is to address all suggestions.' Dr. Hector: 'The grouping is perfect.' Evidence table still needed to verify AI suggestions.", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "Aegis providers"],
  ["Risk / Dx", "Workflow", "Dr. Maharaja", "Adds all diagnoses via PL first with personal templates, then opens Navina only if there are still open hints", "'If there are no hints I won't open Navina.' Uses Dragon for recording. Navina used only to close remaining HCC gaps not already in PL.", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "SFP — Dr. Maharaja"],
  ["Risk / Dx", "Auto-Doc", "Dr. Monica Willson & Group", "Auto-doc V0 feedback: very helpful, especially seeing last eye exam date for DM", "Save+Push is annoying double-click — redundant. Must be in bullets. 'Please for any labs always put 2 recent results so we can see the trend.' Evidence table still needed even with assessment text.", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "CVFP providers"],
  ["Risk / Dx", "Auto-Doc Style", "Multiple providers", "Show assessment text always, even if one-liner", "Missing info is crucial — want it shown as alert/reminder OR as template bullets to fill in. 'Show missing as bullets: Eye exam - Missing, Foot exam - Missing' (Dr. Maharaja). Configure per doctor.", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "All providers (Sep 25)"],
  ["Risk / Dx", "Suggesting Logic", "Multiple providers", "If rejected → don't resurface next year", "'When I reject something, I do it to teach the AI it's a mistake' (Dr. Elder). 'Don't show me something I already rejected based on the same evidence' (CVFP). Time-limited diagnoses concept validated.", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "All providers (Sep 25)"],
  ["Risk / Dx", "Condition-Based vs Task-Based", "Multiple providers", "Majority prefer task-based approach (same as today)", "Most don't want quality gaps as primary content — 'adds noise.' Dr. Elder: 'In the US providers are required for administrative work so task-based makes more sense.'", "Sep 2025", "", "Notion: Dx Onsite Visit Sep 25", "All providers (Sep 25)"],
  ["Risk / Dx", "HCC / Risk", "Megan (Medical Director, Valley Medical Group)", "What's working: AI reads for heart failure (echo reads) are a clear win", "Live sync highly valued. Information overload: too many obesity/diabetes sub-codes — should condense. Hyperlipidemia appears as companion suggestion with no HCC code — distracting. Confirm button gets buried on scroll — needs to float.", "Jun 2026", "", "Notion: Arches Medical Onsite Jun 26", "Arches Medical"],
  ["Risk / Dx", "ICD / Dropdown", "Destiny, Sarah", "Wants unspecified ICD codes suppressed entirely from suggestions", "Wants unspecified ICD codes suppressed entirely — creating 3-way conflict with ClareMedica (keep as manual fallback) and Upper Line (make default). Must be configurable per org, possibly per condition.", "2026", "", "Notion: DX UXUI Validations AI Summary", "Herself Health"],
  ["Risk / Dx", "ICD / Dropdown", "Yusnier", "Wants unspecified ICD code kept as a manual fallback option", "Wants unspecified ICD code kept as a manual fallback option. Does not want it suppressed. Opposite preference from Herself Health.", "2026", "", "Notion: DX UXUI Validations AI Summary", "ClareMedica"],
  ["Risk / Dx", "ICD / Dropdown", "Joe Haffner, Dr. Chris Tunn, Ryan", "Wants unspecified ICD code as the default selection", "Also surfaced post-scrub HIE-refresh gap: net-new/redundant/negated suggestions appear between coder's scrub and the visit with no clean handling. Evidence should be ranked by clinical relevance not alphabetically.", "2026", "", "Notion: DX UXUI Validations AI Summary", "Upper Line"],
  ["Risk / Dx", "Bulk Actions / ICD", "Becca, Aspen", "Wants multi-select allowed for conditions with legitimately coexisting complications", "On bulk actions: distinguishes Accept All as meaningfully riskier than Reject All / Hold All — fix should be asymmetric gating not all-or-nothing toggle.", "2026", "", "Notion: DX UXUI Validations AI Summary", "Bookmark"],
  ["Risk / Dx", "Bulk Actions", "DTC, HHHN, HarmonyCares, Bookmark, MFM Health, Herself Health, ClareMedica, Upper Line", "Bulk Actions consensus: multiple clients independently distinguish Accept All as riskier than Reject/Hold All", "Pattern is asymmetric — not a binary on/off. Herself Health outright rejects bulk accept.", "2026", "", "Notion: DX UXUI Validations AI Summary", "Multiple clients (8)"],
  ["Risk / Dx", "Workflow", "Clara, Susan, Chuck, Corey, Harmony", "Implementation sync (Mar 24): successful go-live, ~31% WAU early adoption", "Focus on resolving login/admin friction and claims + CPT data ingestion. Weekly sync (Apr 7): adoption trending to ~50% WAP but technical friction + data trust gaps impacting provider experience.", "Mar 2026", "", "Slack: customer-loudoun-medical-group", "Loudoun Medical Group"],
  ["Risk / Dx", "Analytics", "Analytics team", "Slow-burn trust crisis: specialty-office data issue escalated to 4th request by April 30", "Analytics ticket analysis shows action hierarchy (Not Addressed < Held < Reject < Accept). Key gap: documentation vs. in-product guidance.", "2026", "", "Slack: customer-loudoun-medical-group; Notion: Analytics tickets analysis", "Loudoun Medical Group"],
  ["Risk / Dx", "Onsite Visit", "Clara (ACO leader) + 4 offices", "Onsite Jun 16-17: ACO since 2014, $17M+ in savings but not getting share due to undercoding", "Providers see 12-15 patients/day. Strong engagement when visited in person — coaching and education on Navina highly valued.", "Jun 2026", "", "Slack: customer-loudoun-medical-group", "Loudoun Medical Group"],
  ["Risk / Dx", "Workflow", "Fran, Yusnier, Janice, Yordan", "Weekly sync (Apr 3): eCW overnight update caused unexpected changes — trust issue", "Weekly sync (May 29): Health status yellow — green relationship but waiting for Business Review to move fully green. Ticket volume had a cliff (positive sign — issues resolving).", "Apr 2026", "", "Slack: customer-claremedica-health-partners-fka-caremax", "ClareMedica (fka CareMax)"],
  ["Risk / Dx", "Workflow", "Raul, Virginia, Patricia, Araly", "Bi-weekly (Jul 2025): Risk adjustment review — discussing HCC capture and CDI team workflows", "Bi-weekly (Jan 2026): outage caused large ignored list — hard to distinguish true provider ignores. Analytics ticket analysis: ~22% of ticket volume from InnovaCare — 8 near-identical 'please remove these visits from reporting' requests.", "2025-2026", "", "Slack: customer-innovacare-health; Notion: Analytics tickets analysis", "InnovaCare"],
  ["Ambient", "Workflow", "5 providers + 2 medical scribes", "Providers don't use laptops in exam rooms — primarily iPads or scribes with laptops", "Makes daily tool usage difficult without mobile version. Mobile app confirmed critical for adoption. ~40% Hispanic population → Spanish language support a must-have.", "Aug 2025", "", "Notion: V0 Go Live Onsite Aug 25", "First Valley Medical Group"],
  ["Ambient", "Product Feedback", "Providers", "Excited about tool", "Several successful accurate notes. Good recording experience. Clunky code editing: suggestions dropdown unclear. ICD push failures (SNOMED issue). Note editor lacks contrast.", "Aug 2025", "", "Notion: V0 Go Live Onsite Aug 25", "First Valley Medical Group"],
  ["Ambient", "Product Feedback", "Lynn + providers", "Overall positive reception", "Main advantage over Freed: deep EHR integration. Consolidated note feature seen as 'game-changer.' Mobile flexibility essential. Lynn: notes 'too concise.' ICD matching must use Problem List.", "Aug 2025", "", "Notion: V0 Go Live Onsite Aug 25", "DTC Family Health"],
  ["Ambient", "Product Feedback", "Providers, Jessica/Brittany (admin)", "Strong positive reception — 'Where has this been my whole life?'", "Note quality highly impressive. Patient Instructions: major hit. Surpasses embedded SUKI product (confirmed by head of implementation Jennifer). ICD empty state UX unclear. Patient consent reminder missed by some providers.", "Aug 2025", "", "Notion: V0 Go Live Onsite Aug 25", "HHHN"],
  ["Ambient", "Future Needs", "Dr. Bill Borgos + providers", "Patient Instructions are standout feature — accurate, rarely need edits", "AWVs struggle — misses social context (retirement, caregiving, routines). Wants ROS separate from PE. A&P good only when diagnoses pre-charted. ICD search non-semantic — frustrating.", "Dec 2025", "", "Notion: Clients meetings summaries — HHHN Dr. Borgos", "HHHN"],
  ["Ambient", "Ongoing Feedback", "Lynn", "Feb 2024: still using Freed VIM overlay (mobile recording preferred)", "Apr 2025: excited about pushing to correct structured EMR fields — unlike Suki. 'Editing within EMR will still be necessary.' Very enthusiastic after demo — particularly about note structure matching pre-documented codes.", "2024-2025", "", "Notion: Clients meetings summaries — DTC", "DTC Family Health"],
  ["Ambient", "Ongoing Feedback", "Jenn", "Ambient for MA: liked the idea — 'as far as she knows other solutions don't do it — can be our edge'", "Patient comes in and starts talking regardless of who — many things won't be repeated to provider. Would expect MA discussion in HPI, then provider adds upon it.", "Mar 2025", "", "Notion: Clients meetings summaries — NOMS", "NOMS"],
  ["Ambient", "Workflow", "Dr. Bower", "Uses phone to record (only option)", "Limitations: forgets phone, battery dies, unexpected stops. 'Pajamas time much shorter.' Wants more integrated EHR data. Would love Navina to predict diagnoses based on ambient.", "2025", "", "Notion: User feedback on other Ambient tools", "NOMS — Dr. Bower"],
  ["Ambient", "Workflow", "Dr. Hochman", "Uses DAX for ALL patients", "Prefers computer recording over phone. Edits note immediately after visit. MA no longer needs to document patient history — saves ~1 hour/day. Verbal consent for every patient.", "2025", "", "Notion: User feedback on other Ambient tools", "NOMS — Dr. Hochman (Jenn)"],
  ["Ambient", "Workflow", "Sarah, NP", "Satisfaction: 10/10", "Uses for HPI only initially. Shortens visits. Rarely edits generated summary. Previously used Dragon and hated it. 'Now I have significantly more free time.'", "2025", "", "Notion: User feedback on other Ambient tools", "NOMS — Sarah (NP)"],
  ["Ambient", "Adoption", "Stewart, Kim, Phuong, Nicole", "Weekly sync (Jul 24): 1-hour portrait refresh + same-day appointments — ticket #27713 open", "Analytics refresh delay raised by Nicole. Jul 28: Patient-based analytics beta feedback coming in mostly through various channels.", "Jul 2026", "", "Slack: customer-harmonycares", "HarmonyCares"],
  ["Ambient", "Adoption", "Providers + leadership", "Ambient sync (Jul 9): 50% active users that week", "Of those 50%, ~70% of encounters where Navina was available were recorded. Of those recorded, ~79% were pushed to EHR. Risk + Quality + Ambient live simultaneously.", "May 2026", "", "Slack: customer-the-harbor-health-team", "Harbor Health"],
  ["Ambient", "Pilot Feedback", "Arett Zartarian (COO), Dr. Wheaton, Jillian", "Discovery call (Jun 15): all providers currently using Freed — evaluating Navina as replacement not parallel", "Key Freed features expected: provider-specific note templates (Navina has this), AI document chat to summarize hospital discharge summaries (gap — not yet in Navina). KPIs: engagement/adoption rate, time in chart, provider satisfaction.", "Jun 2026", "", "Notion: Rancho Health Ambient Discovery Call", "Rancho Health"],
  ["Ambient", "Onsite Feedback", "MDs, DOs, NPs, scribes, leadership — 5 clinics", "Onsite Jul 27-28: highly productive, strong engagement 5 weeks post go-live", "Dr. Wheaton: some providers who invested heavily customizing Freed are resistant to switching — sunk cost barrier. Aug 14: V28-only roster mapping agreed, quality measure config reviewed, HIE activation targeted for Monday.", "Jul 2026", "", "Slack: customer-rancho-family-medical-group", "Rancho Health"],
  ["Competitive", "Ambient — Suki", "Dr. Dodd", "Uses Suki — satisfied", "Prefers web app over mobile. Suki auto-imports EHR data but doesn't summarize. Note generated in 30-45 secs. Cost: $399/month. Warning: 'They are going into your space' — Suki moving into risk adjustment.", "Nov 2024", "", "Notion: User feedback on other Ambient tools", "CVFP — Dr. Dodd"],
  ["Competitive", "Ambient — Freed/Suki", "Lynn Joffe", "Stopped using Athena alpha (Suki-based): confabulated, missed dates, didn't learn styling", "Freed via Vim overlay: $35 extra/month. Freed has no ICD suggestions at all. Navina demo: excited about note structure matching pre-charted codes — 'this will change the lives of providers more than anything else you do.'", "2024-2025", "", "Notion: User feedback on other Ambient tools", "DTC — Lynn"],
  ["Competitive", "Ambient — Ambience", "Clinical team", "Ambience is best product seen for EMR integration, workflow, ICD suggestions", "Almost all providers using it. Ambience vs. Suki: Ambience more thorough/narrative, Suki more bullet-pointed. Left Ambience due to customer support issues. Suki: $400/PPPM. Works alongside Navina for pre-visit (Navina) + during-visit recording (Ambience).", "Jan 2025", "", "Notion: User feedback on other Ambient tools", "Herself Health"],
  ["Competitive", "Ambient — Nabla", "Tyler, Aaron, Dr. Sides (rheumatologist)", "~5 providers using Nabla (very low percentage)", "Main barrier: have to copy note into eCW — not seamless. Does a great job leaving small talk out of notes. 'If the EMR integration happened, adoption would be greater.'", "Jan 2025", "", "Notion: User feedback on other Ambient tools", "JCMG"],
  ["Competitive", "Ambient — Suki", "Dr. Gallagher, Jennifer Muhammad (Head of Implementation)", "Few providers on free trial (2-4)", "A/P section limitation: pushes A/P as one paragraph to first empty textbox — deal-breaker. Helps retain/recruit physicians. Pajamas time dashboard tracks off-hours — key metric for them.", "Jan 2025", "", "Notion: User feedback on other Ambient tools", "HHHN"],
  ["Agentic", "Trust", "Stephanie Clements, Laura Stankovic", "Comfortable with AI 'tee it up for approval or dismissal' approach", "Explicit: AI should NOT push final documentation without human approval. Build manual workflows first, then agent layer on top with user choice of auto-execute vs. preview-and-approve.", "Jun 2026", "", "Notion: CareMore Onsite Jun 26", "CareMore"],
  ["Pop Health", "Workflow", "Care Manager / Care Team", "Data is simultaneously too much and not enough — real-time ADT dedup is the core ask", "Users get 25 alerts for a single admission. The pain is not lack of data but lack of a clean, deduplicated, real-time feed. EMR, pop health tool, and CRM (e.g. Salesforce) all siloed — forcing duplicate entry and manual workarounds.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Workflow", "Care Manager", "Inability to separate high-cost vs. high-risk patients is the #1 prioritization failure", "Teams with limited staff cannot identify which patients need attention most urgently. Existing tools flag patients who are already high-cost — too late to act. The real opportunity is identifying 'suffering in silence' patients who are clinically at risk but not yet seeking care.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Workflow", "Care Manager", "Post-discharge → TCM workflow is manual, time-sensitive, and chronically broken", "Disconnect between hospitalists and primary care on discharge planning. Manual TCM workflows create missed 48h/14-day windows. Specialty referrals are made based on familiarity ('who I know'), not data on cost or quality.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Workflow", "Provider", "Providers don't understand what they're being told to do — and ignore it", "Providers lack context and rationale behind VBC action requests. The mindset shift from fee-for-service is a major hurdle. Any tool requiring extra clicks or a separate portal faces abandonment — must be embedded in the natural workflow.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Data / Integration", "VBC Leader / Manager", "Existing pop health tools are claims-first and retrospective — not built for frontline use", "Competitors (Lightbeam, Arcadia, Innovaccer) were built as back-office ACO reporting tools and bolted on clinical features. Their core remains retrospective. Navina's origin at point of care is a structural advantage competitors cannot close without rebuilding from scratch.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Trust", "VBC Leader / Manager", "Vendors promise integration but deliver shallow overlays — trust erodes fast", "Data is often not wrong but late, fragmented, or inconsistent across modules of the same platform. Large vendors grew through acquisition — internal systems 'don't talk well to each other.' Proprietary 'black box' logic is a major red flag for sophisticated buyers.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Goals", "VBC Leader", "Roadmap vote top 3: #1 Unified Risk Stratification, #2 Multi-dept patient view, #3 Right insight to right user", "Mentimeter vote results across all workshop participants: Top 1 — Unified Risk Stratification Engine; Top 2 — Multi-department patient view (Risk + Quality + Care Mgmt); Top 3 — Deliver the right insight to the right user at the right time. These ranked highest on both impact and prevalence.", "Nov 2025", "", "Drive: Pop health advisors workshop - Nov25 (Mentimeter results)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Goals", "VBC Leader / Manager", "Key metrics: PMPM, admissions/readmissions per 1K, MLR, TCM completion rate — layered by persona", "Leadership needs PMPM cost vs. benchmark, MLR trend, utilization trends (dashboards). Providers need 1-2 simple, compensation-tied metrics directly in workflow — not dashboards. TCM completion rate (48h call / 14-day visit) is a critical operational metric all agreed on.", "Nov 2025", "", "Drive: Population Health Strategy and Product Definition (Nov25)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Pricing / WTP", "VBC Leader / Manager", "Financial case: 20% reduction in inpatient + ED utilization ≈ $65 PMPM, ~5-point MLR improvement", "For a 100K-member book, every 1 MLR point = $4–16M/year depending on premium levels. MLR + RAF improvement together are the strongest indicators of mature VBC performance. That performance gap dwarfs most other operating levers and anchors the ROI conversation.", "Nov 2025", "", "Drive: PopHealth Strategy (Nov 2025)", "Pop Health Advisors Workshop"],
  ["Pop Health", "Workflow", "Care Manager / Admin (Gary Pilling — External Advisor)", "IPG care management needs real-time ADT, team performance vs. benchmark, unified stratification — one platform", "For independent physician groups: head of care management needs real-time ADT tracking, team performance vs. benchmark, elevated patient tier outcomes, overall utilization. MVP must-haves: EMR + platform integrations, customizable stratification, workflow flexibility. Navina's edge: point-of-care delivery combined with care management workflow coordination.", "Nov 2025", "", "Drive: PopH workshop - value matrix", "Pop Health Advisors Workshop (Gary Pilling)"],
  ["Pop Health", "Workflow", "Care Manager / CMO (Carlos Rodriguez — Aegis)", "IPG care management needs actionable patient stratification with real-time admissions data — without adding burden to providers", "Key features: patient stratification, utilization understanding per patient, easy provider interaction, data sharing across quality and risk departments, real-time admissions data. Navina's edge: EHR integration + user-friendly system. 'Predictive future trainwrecks' (patients with multiple conditions + SDOH) cited as a strong differentiator.", "Nov 2025", "", "Drive: PopH workshop - value matrix", "Pop Health Advisors Workshop (Carlos Rodriguez / Aegis)"],
  ["Pop Health", "Workflow", "VBC Leader — Health System (Steve Simpson, Navina)", "Health systems need integrated workflow + proven high clinician adoption — insights must be pushed to point of action", "VP Pop Health needs: integrated and enhanced workflow, reduction in cost/util, clinician satisfaction, improved patient outcomes. Must-have: high clinician adoption with insights pushed to the right resource at point of action. Navina's edge: proven integration into existing clinical workflows + world-class AI engine.", "Nov 2025", "", "Drive: PopH workshop - value matrix", "Pop Health Advisors Workshop (Steve Simpson)"],
  ["Pop Health", "Workflow", "VBC Leader — ACO/MSO Executive Director (Zac Oty, Navina)", "ACO/MSO executive directors need proactive stratification + reactive utilization insights + justification for shared savings fees", "Proactive needs: cohort patients via risk stratification, identify rising risk patients. Reactive needs: utilization trends, identify problems to direct staff to practices. MVP must-haves: point of action, stratification, ADT notifications, attribution, action plans, TIN-level MLR performance. Navina's edge: single vendor for multiple VBC needs, replacing bolt-on software stacks.", "Nov 2025", "", "Drive: PopH workshop - value matrix", "Pop Health Advisors Workshop (Zac Oty)"],
  ["Pop Health", "Workflow", "CMO — Payer (Jonathan Meyers — External Advisor)", "Payers need clinical tiers for care management efficiency + EMR-agnostic integration across provider networks", "Payer CMO needs: clinical tiers to maximize care management resources, effective patient-specific guidance for program implementation. Navina's edge: proven integration into several EMRs — key for payers who fund the tool for members without controlling the provider's EMR.", "Nov 2025", "", "Drive: PopH workshop - value matrix", "Pop Health Advisors Workshop (Jonathan Meyers)"],
  ["Analytics", "Goals", "Carlos Rodriguez (Head of Care Management, Aegis)", "RAF score alone is insufficient — need to show what drives it: recapture, suspects, and open opportunity", "Good high-level snapshot but missing trend over time and membership growth/decline. RAF needs context: show how much comes from recapture, suspects, and open opportunity — not just the number. Recapture and Suspect metrics are very important for financial and operational tracking. Carlos recommends including both Avg RAF and Recapture rate on the overview page.", "Feb 2026", "", "Notion: POP user feedback", "Aegis"],
  ["Analytics", "Goals", "Carlos Rodriguez (Aegis)", "Financial impact formula: HCC × $ value × 12 months = PMPM impact — this logic should be reflected in the dashboard", "This is the formula Carlos uses to translate clinical capture into financial value. The dashboard should surface recapture rate as a primary KPI, show patients seen instead of patients without visit, and provide a clear link between metrics and revenue impact.", "Feb 2026", "", "Notion: POP user feedback", "Aegis"],
  ["Analytics", "Trust", "Carlos Rodriguez (Aegis)", "'Potential RAF based on all patients' is misleading — creates unrealistic expectations", "Not all patients will have visits, not all suspects will be confirmed, and some diagnoses reviewed are not approved. Recommendation: remove full potential RAF or clearly mark it as theoretical maximum. Membership growth or decline is also not shown and is important.", "Feb 2026", "", "Notion: POP user feedback", "Aegis"],
  ["Analytics", "Workflow", "Carlos Rodriguez (Aegis)", "Top Opportunities section is very important but needs clear prioritization, RAF/financial impact per opportunity, and estimated effort", "Carlos wants to use Top Opportunities as a work queue. Currently missing: clear prioritization logic, RAF or financial impact per opportunity, estimated effort. Outstanding HCC gaps over time is a strong operational KPI — could add target line (Carlos targets: Q1:50%, Q2:75%, Q3:90%, Q4:93%).", "Feb 2026", "", "Notion: POP user feedback", "Aegis"],
  ["Analytics", "Goals", "Joe Hefner (VBC Leader, Upperline)", "Top 3 metrics: Avg RAF, Recapture rate, Address rate (with breakdown: capture + reject + pause)", "Clean and clear overview — similar to what he builds with actuaries today. Wants: year-over-year comparison added, monthly trend to show improvement, annual churn rate, MA vs. ACO regional segmentation. Also wants: patients without a visit and patients with an upcoming visit.", "Feb 2026", "", "Notion: POP user feedback", "Upperline Health"],
  ["Analytics", "Workflow", "Joe Hefner (Upperline)", "Risk Adjustment Performance section is 'super helpful' — helps model acceptance rates and predict future RAF", "He already uses similar logic in actuarial models. Helps model acceptance rates, predict future RAF, and supports forward planning. Top Opportunities saves analyst work and provides a weekly action list. Would prioritize opportunities by: 1) financial impact, 2) clinical impact.", "Feb 2026", "", "Notion: POP user feedback", "Upperline Health"],
  ["Analytics", "Workflow", "Joe Hefner (Upperline)", "Missing filters: regional (very important), provider, and market — regional managers need their own performance view", "Regional managers need to see their own performance. Provider performance metrics needed: address rate per provider, rejection rates, pause rates — and these should connect to opportunities. User personas require different dashboard versions: C-level (high-level KPIs), regional leaders (region view), clinic managers (provider level), outreach teams (workspace only).", "Feb 2026", "", "Notion: POP user feedback", "Upperline Health"],
  ["Analytics", "Data / Integration", "Joe Hefner (Upperline)", "Large orgs already use tools like RoundingWell for outreach — will Navina offer integrations or API?", "One source of truth with no need to combine multiple systems is the core value. Workspace saves analyst work and supports outreach workflows. Challenge: large organizations already have call centers and outreach tools. API/integration path is the realistic adoption route for these orgs.", "Feb 2026", "", "Notion: POP user feedback", "Upperline Health"],
  ["Analytics", "Workflow", "Scot (POC, Revere Medical Group)", "Most important metric: RAF captured vs. potential RAF — needs drill-down to patient level with current RAF, potential RAF, last/next visit, previous year RAF", "Address Rate, Capture Rate, and Recapture Rate are important and used often. Most important: RAF captured vs. potential RAF with patient-level drill-down. For the plan breakdown, showing RAF models (V28 vs HHS) is sufficient — Medicaid visibility also important. Outstanding HCC gaps chart is useful but least important component on the page.", "Mar 2026", "", "Notion: POP user feedback", "Revere Medical Group"],
  ["Analytics", "Workflow", "Scot (Revere Medical Group)", "For HCC follow-up patients, need to see scheduled vs. not-scheduled visits to know who to contact first", "The three top tiles are very useful: Total patients, Patients without a visit with HCC gaps, and Seen patients requiring HCC follow-up. Total patients trend would be more helpful monthly instead of yearly. For HCC follow-up, scheduled vs. not-scheduled split determines outreach priority.", "Mar 2026", "", "Notion: POP user feedback", "Revere Medical Group"],
  ["Analytics", "Goals", "Scot (Revere Medical Group)", "Star ratings: show how many patients are needed to reach the next star tier (e.g. 3→4 stars), not just percentages", "Quality tiles are very helpful: quality performance, care gaps ready for payer submission, patients missing AWV — each must link to the patient list. For potential star ratings, showing how many patients are needed to reach the next star rating is more actionable than percentages alone.", "Mar 2026", "", "Notion: POP user feedback", "Revere Medical Group"],
  ["Analytics", "Workflow", "Scot (Revere Medical Group)", "Outreach call notes must sync back to the EMR — clinic staff need to know why the patient was contacted", "Top opportunities list is very relevant and would be used daily. Having one combined workspace for risk and quality is very valuable so multiple teams don't contact the same patient. Currently uses campaigns (portal/email/SMS) for large groups and phone calls for specific patients. If calls are done from Navina, call notes must go back to the EMR.", "Mar 2026", "", "Notion: POP user feedback", "Revere Medical Group"],
];

async function main() {
  console.log("Seeding discovery questions...");
  let qCount = 0;
  for (const row of DISCOVERY_QUESTIONS) {
    const [productAreaRaw, themeRaw, persona, question, notesIntent, source] = row;
    if (!question?.trim()) continue;
    const id = hashId("q", question);
    await prisma.discoveryQuestion.upsert({
      where: { id },
      create: {
        id,
        productArea: mapProductArea(productAreaRaw ?? ""),
        theme: mapTheme(themeRaw ?? ""),
        persona: persona?.trim() || null,
        question: question.trim(),
        notesIntent: notesIntent?.trim() || null,
        source: source?.trim() || null,
      },
      update: {},
    });
    qCount++;
  }
  console.log(`  ✓ ${qCount} discovery questions`);

  console.log("Seeding client feedback...");
  let iCount = 0;
  for (const row of INSIGHTS) {
    const [productAreaRaw, themeRaw, persona, oneLiner, content, date, wtp, source, client] = row;
    if (!oneLiner?.trim()) continue;
    const id = hashId("ins", `${client}${oneLiner}`);
    await prisma.insight.upsert({
      where: { id },
      create: {
        id,
        productArea: mapProductArea(productAreaRaw ?? ""),
        theme: mapTheme(themeRaw ?? ""),
        persona: persona?.trim() || null,
        oneLiner: oneLiner.trim(),
        content: content?.trim() || oneLiner.trim(),
        client: client?.trim() || null,
        sourceName: source?.trim() || null,
        sourceType: "SHEET",
        date: parseDate(date ?? ""),
        wtp: wtp?.trim() || null,
        tags: "[]",
      },
      update: {},
    });
    iCount++;
  }
  console.log(`  ✓ ${iCount} client feedback entries`);

  console.log(`\nDone! Seeded ${qCount} questions + ${iCount} insights.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
