-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "aliases" TEXT NOT NULL DEFAULT '[]',
    "createdBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Account_name_key" ON "Account"("name");

-- AlterTable
ALTER TABLE "Insight" ADD COLUMN "clientRaw" TEXT;

-- Seed the canonical client list from Navina's accounts report (Aug 2026).
-- ON CONFLICT so re-running against a database that already has them is a no-op.
INSERT INTO "Account" ("id", "name", "aliases") VALUES
  ('acct-advisors', 'Advisors', '["Advisor","Advisory","Advisory Board","Pop Health Advisors","Pop Health Advisors Workshop"]'),
  ('acct-adventist-healthcare', 'Adventist Healthcare', '[]'),
  ('acct-aegis-medical-group', 'Aegis Medical Group', '["Aegis"]'),
  ('acct-agilon-health', 'agilon health', '["agilon"]'),
  ('acct-alliance-for-integrated-care-of-new-york', 'Alliance for Integrated Care of New York', '["AICNY","Alliance for Integrated Care"]'),
  ('acct-amite-county-medical-services', 'Amite County Medical Services', '[]'),
  ('acct-archesmed', 'ArchesMed', '["Arches","Arches Medical","Arches Medical Onsite"]'),
  ('acct-atlas-oncology-partners', 'Atlas Oncology Partners', '[]'),
  ('acct-bookmark-medical', 'Bookmark Medical', '["Bookmark","Rural Healthcare Group"]'),
  ('acct-cano-health', 'Cano Health', '[]'),
  ('acct-cardiovascular-associates-of-america', 'Cardiovascular Associates of America', '[]'),
  ('acct-carle-health', 'Carle Health', '[]'),
  ('acct-carolina-pines-regional-medical-center', 'Carolina Pines Regional Medical Center', '[]'),
  ('acct-catalyst-health-group', 'Catalyst Health Group', '[]'),
  ('acct-center-for-primary-care', 'Center for Primary Care', '[]'),
  ('acct-christie-clinic', 'Christie Clinic', '[]'),
  ('acct-citadel', 'Citadel', '["Aylo","Aylo Health","Eagles Landing Health"]'),
  ('acct-claremedica-health-partners', 'ClareMedica Health Partners', '["ClareMedica","CareMax","Caremax"]'),
  ('acct-convenientmd', 'ConvenientMD', '[]'),
  ('acct-cvfp-medical-group', 'CVFP Medical Group', '["CVFP"]'),
  ('acct-doctors-health-of-south-florida', 'Doctors Health of South Florida', '[]'),
  ('acct-dtc-family-health', 'DTC Family Health', '["DTC"]'),
  ('acct-edinger-medical-group', 'Edinger Medical Group', '[]'),
  ('acct-evergreen-nephrology', 'Evergreen Nephrology', '[]'),
  ('acct-family-practice-of-cadillac', 'Family Practice of Cadillac', '[]'),
  ('acct-first-medical-associates', 'First Medical Associates', '["Doctors First"]'),
  ('acct-first-valley-medical-group', 'First Valley Medical Group', '[]'),
  ('acct-gather-health', 'Gather Health', '[]'),
  ('acct-genuine-health-group', 'Genuine Health Group', '[]'),
  ('acct-glacier-medical-associates', 'Glacier Medical Associates', '[]'),
  ('acct-granger-medical-clinic', 'Granger Medical Clinic', '[]'),
  ('acct-greater-good-health', 'Greater Good Health', '[]'),
  ('acct-harmonycares', 'HarmonyCares', '["Harmony Cares","Harmony"]'),
  ('acct-healthstar-physicians', 'HealthStar Physicians', '["HealthStar"]'),
  ('acct-healthtexas-medical-group', 'HealthTexas Medical Group', '["HealthTexas"]'),
  ('acct-herself-health', 'Herself Health', '[]'),
  ('acct-holzer-health-system', 'Holzer Health System', '["Holzer"]'),
  ('acct-hopscotch-primary-care', 'Hopscotch Primary Care', '["Hopscotch"]'),
  ('acct-hudson-headwaters-health-network', 'Hudson Headwaters Health Network', '["HHHN","Hudson Headwaters"]'),
  ('acct-ilumed', 'Ilumed', '[]'),
  ('acct-ima-medical-group', 'iMA Medical Group', '[]'),
  ('acct-ima-of-south-florida', 'IMA of South Florida', '[]'),
  ('acct-innovacare-health', 'Innovacare Health', '["InnovaCare"]'),
  ('acct-internal-medicine-associates-specialties', 'Internal Medicine Associates & Specialties', '[]'),
  ('acct-intracare-premier-aco', 'IntraCare Premier ACO', '["IntraCare"]'),
  ('acct-jefferson-city-medical-group', 'Jefferson City Medical Group', '["JCMG"]'),
  ('acct-kaiser-foundation-health-plan-of-colorado', 'Kaiser Foundation Health Plan of Colorado', '[]'),
  ('acct-kaiser-foundation-health-plan-of-the-mid-atlantic-states', 'Kaiser Foundation Health Plan of the Mid-Atlantic States', '[]'),
  ('acct-kaiser-permanente-nevada', 'Kaiser Permanente Nevada', '[]'),
  ('acct-lifespark', 'Lifespark', '[]'),
  ('acct-loudoun-medical-group', 'Loudoun Medical Group', '["Loudoun","LMG"]'),
  ('acct-matter-health', 'Matter Health', '[]'),
  ('acct-medical-consultants-of-florida', 'Medical Consultants of Florida', '["MCF"]'),
  ('acct-medisys-health-network', 'MediSys Health Network', '["MediSys"]'),
  ('acct-mednetone-health-solutions', 'MedNetOne Health Solutions', '["MedNetOne"]'),
  ('acct-mfm-health', 'MFM Health', '["MFM"]'),
  ('acct-mid-atlantic-permanente-medical-group', 'Mid-Atlantic Permanente Medical Group', '[]'),
  ('acct-millennium-physician-group', 'Millennium Physician Group', '["MPG","Millennium"]'),
  ('acct-mirra-health-services', 'Mirra Health Services', '["Mirra"]'),
  ('acct-mountain-laurel-medical-center', 'Mountain Laurel Medical Center', '["Mountain Laurel"]'),
  ('acct-neuehealth-mso', 'NeueHealth MSO', '["NeueHealth"]'),
  ('acct-north-east-medical-services', 'North East Medical Services', '[]'),
  ('acct-northern-ohio-medical-specialists-healthcare', 'Northern Ohio Medical Specialists Healthcare', '["NOMS"]'),
  ('acct-northwest-permanente-physicians', 'Northwest Permanente Physicians', '["Kaiser Permanente Northwest Physicians"]'),
  ('acct-ogden-clinic', 'Ogden Clinic', '["Ogden"]'),
  ('acct-olmsted-medical-center-physicians', 'Olmsted Medical Center Physicians', '["Olmsted"]'),
  ('acct-on-belay-health-solutions', 'On Belay Health Solutions', '["On Belay"]'),
  ('acct-onpoint-medical-group', 'OnPoint Medical Group', '["OnPoint"]'),
  ('acct-osvaldo-a-torres-md', 'Osvaldo A Torres MD', '[]'),
  ('acct-palm-medical-centers', 'Palm Medical Centers', '["Palm Medical","Health Holdings"]'),
  ('acct-physicians-primary-care', 'Physicians Primary Care', '[]'),
  ('acct-primary-medical-care-center-and-urgent-care-clinic', 'Primary Medical Care Center and Urgent Care Clinic', '[]'),
  ('acct-primehealth-physicians', 'PrimeHealth Physicians', '["PrimeHealth"]'),
  ('acct-primus-health-network', 'Primus Health Network', '["Primus"]'),
  ('acct-privia-health', 'Privia Health', '["Privia"]'),
  ('acct-rancho-family-medical-group', 'Rancho Family Medical Group', '["Rancho","Rancho Health"]'),
  ('acct-sc-house-calls', 'SC House Calls', '[]'),
  ('acct-sfp-health-group', 'SFP Health Group', '["SFP"]'),
  ('acct-southeast-primary-care-partners', 'Southeast Primary Care Partners', '["Southeast","SEMG"]'),
  ('acct-sprinter-health', 'Sprinter Health', '["Sprinter"]'),
  ('acct-summit-medical-group', 'Summit Medical Group', '["Summit"]'),
  ('acct-tampa-general-hospital', 'Tampa General Hospital', '["TGH","Tampa General"]'),
  ('acct-tecq-partners', 'TECQ Partners', '["TECQ"]'),
  ('acct-the-harbor-health-team', 'The Harbor Health Team', '["Harbor Health Team","Harbor Health"]'),
  ('acct-trivalley-medical-group', 'TriValley Medical Group', '[]'),
  ('acct-trivalley-primary-care', 'TriValley Primary Care', '[]'),
  ('acct-tryon-medical-partners', 'Tryon Medical Partners', '["Tryon"]'),
  ('acct-tufts-medicine', 'Tufts Medicine', '["Tufts","Wellforce"]'),
  ('acct-u-s-renal-care', 'U.S. Renal Care', '["US Renal Care","USRC"]'),
  ('acct-unimed-healthcare', 'UniMed HealthCare', '["UniMed"]'),
  ('acct-upperline-health', 'Upperline Health', '["Upperline","Upper Line"]'),
  ('acct-upward-health', 'Upward Health', '["Upward"]'),
  ('acct-valora-medical-group', 'Valora Medical Group', '["Valora"]'),
  ('acct-vanguard-medical-group', 'Vanguard Medical Group', '["Vanguard"]'),
  ('acct-villagemd', 'VillageMD', '["Village MD"]'),
  ('acct-washington-permanente-medical-group', 'Washington Permanente Medical Group', '["Kaiser Permanente Washington Physicians"]')
ON CONFLICT ("name") DO NOTHING;
